// template/dreamspos-v2.2.4/food-pos-vue-extracted/vue/template/src/components/modal/tax-settings-modal.vue
<template>
    <!-- Add Category -->
    <div class="modal fade" id="add_tax">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header border-0 p-4 pb-3">
                    <h4 class="modal-title">Add Tax</h4>
                    <button type="button" class="btn-close btn-close-modal" data-bs-dismiss="modal" aria-label="Close"><i class="icon-x"></i></button>
                </div>
                <form action="#">                             
                    <div class="modal-body p-4 pt-1">
                        <div class="mb-3">
                            <label class="form-label">Title<span class="text-danger"> *</span></label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Tax Rate (%)<span class="text-danger"> *</span></label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Tax Type<span class="text-danger"> *</span></label>
                            <vue-select 
                                :options="Tax"
                                v-model="selected"
                                placeholder="Select"
                            />
                        </div>
                        <div class="d-flex align-items-center justify-content-between gap-2 pt-1">
                            <button type="button" class="btn btn-light w-100" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary w-100">Save</button>
                        </div>
                    </div>
                </form>     
            </div>
        </div>
    </div>
    <!-- Add Category End -->

    <!-- Edit Category -->
    <div class="modal fade" id="edit_tax">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header border-0 p-4 pb-3">
                    <h4 class="modal-title">Edit Tax</h4>
                    <button type="button" class="btn-close btn-close-modal" data-bs-dismiss="modal" aria-label="Close"><i class="icon-x"></i></button>
                </div>
                <form action="#">                             
                    <div class="modal-body p-4 pt-1">             
                        <div class="mb-3">
                            <label class="form-label">Title<span class="text-danger"> *</span></label>
                            <input type="text" class="form-control" value="Inclusive / Exclusive">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Tax Rate (%)<span class="text-danger"> *</span></label>
                            <input type="text" class="form-control" value="9%">
                        </div>
                        <div class="mb-3">
                            <label class="form-label">Tax Type<span class="text-danger"> *</span></label>
                            <vue-select 
                                :options="Tax"
                                v-model="selectedOne"
                                placeholder="Select"
                            />
                        </div>
                        <div class="d-flex align-items-center justify-content-between gap-2 pt-1">
                            <button type="button" class="btn btn-light w-100" data-bs-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary w-100">Save</button>
                        </div>
                    </div>
                </form>     
            </div>
        </div>
    </div>
    <!-- Edit Category End -->
</template>

<script>
export default {
    data(){
        return {
            selected: [],
            selectedOne: "CGST",
            Tax: [
                { label: "Select", value: "Select" },
                { label: "CGST", value: "CGST" },
                { label: "SGST", value: "SGST" },
                { label: "IGST", value: "IGST" },
                { label: "VAT", value: "VAT" },
                { label: "Service Tax", value: "Service Tax" },
            ]
        }
    }
}
</script>

// template/dreamspos-v2.2.4/food-pos-react-extracted/react/template/src/pages/settings/tax-settings/taxSettingsModal.tsx

import {  TaxType } from "../../../core/json/selectOption"
import CommonSelect from "../../../components/common-select/commonSelect"

const TaxSettingsModal = () => {

    return (
        <>
            {/* Add Category */}
            <div className="modal fade" id="add_tax">
                <div className="modal-dialog modal-dialog-centered">
                    <div className="modal-content">
                        <div className="modal-header border-0 p-4 pb-3">
                            <h4 className="modal-title">Add Tax</h4>
                            <button
                                type="button"
                                className="btn-close btn-close-modal"
                                data-bs-dismiss="modal"
                                aria-label="Close"
                            >
                                <i className="icon-x" />
                            </button>
                        </div>
                        <form>
                            <div className="modal-body p-4 pt-1">
                                <div className="mb-3">
                                    <label className="form-label">
                                        Title<span className="text-danger"> *</span>
                                    </label>
                                    <input type="text" className="form-control" />
                                </div>
                                <div className="mb-3">
                                    <label className="form-label">
                                        Tax Rate (%)<span className="text-danger"> *</span>
                                    </label>
                                    <input type="text" className="form-control" />
                                </div>
                                <div className="mb-3">
                                    <label className="form-label">
                                        Tax Type<span className="text-danger"> *</span>
                                    </label>
                                    <CommonSelect
                                        options={TaxType}
                                        className="select"
                                        defaultValue={TaxType[0]}
                                    />
                                </div>
                                <div className="d-flex align-items-center justify-content-between gap-2 pt-1">
                                    <button
                                        type="button"
                                        className="btn btn-light w-100"
                                        data-bs-dismiss="modal"
                                    >
                                        Cancel
                                    </button>
                                    <button type="submit" className="btn btn-primary w-100">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {/* Add Category End */}
            {/* Edit Category */}
            <div className="modal fade" id="edit_tax">
                <div className="modal-dialog modal-dialog-centered">
                    <div className="modal-content">
                        <div className="modal-header border-0 p-4 pb-3">
                            <h4 className="modal-title">Edit Tax</h4>
                            <button
                                type="button"
                                className="btn-close btn-close-modal"
                                data-bs-dismiss="modal"
                                aria-label="Close"
                            >
                                <i className="icon-x" />
                            </button>
                        </div>
                        <form>
                            <div className="modal-body p-4 pt-1">
                                <div className="mb-3">
                                    <label className="form-label">
                                        Title<span className="text-danger"> *</span>
                                    </label>
                                    <input
                                        type="text"
                                        className="form-control"
                                        defaultValue="Inclusive / Exclusive"
                                    />
                                </div>
                                <div className="mb-3">
                                    <label className="form-label">
                                        Tax Rate (%)<span className="text-danger"> *</span>
                                    </label>
                                    <input type="text" className="form-control" defaultValue="9%" />
                                </div>
                                <div className="mb-3">
                                    <label className="form-label">
                                        Tax Type<span className="text-danger"> *</span>
                                    </label>
                                    <CommonSelect
                                        options={TaxType}
                                        className="select"
                                        defaultValue={TaxType[1]}
                                    />
                                </div>
                                <div className="d-flex align-items-center justify-content-between gap-2 pt-1">
                                    <button
                                        type="button"
                                        className="btn btn-light w-100"
                                        data-bs-dismiss="modal"
                                    >
                                        Cancel
                                    </button>
                                    <button type="submit" className="btn btn-primary w-100">
                                        Save
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {/* Edit Category End */}
        </>


    )
}

export default TaxSettingsModal
