// template/react-extracted/react/template/src/pages/authentication/register/register.tsx
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../auth-context/authContext";
import { useEffect, useRef, useState, type FormEvent } from "react";
import Toast from "../../../components/toast/toast";
import { all_routes } from "../../../routes/all_routes";
import ImageWithBasePath from "../../../components/image-with-base-path";
type PasswordField = "password" | "confirmPassword";

const Register = () => {
  const { register } = useAuth();
  const navigate = useNavigate();

  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const [toast, setToast] = useState<{
    msg: string;
    type: "success" | "danger" | "warning" | "info";
  } | null>(null);
  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const showToast = (
    msg: string,
    type: "success" | "danger" | "warning" | "info"
  ) => {
    if (toastTimer.current) {
      clearTimeout(toastTimer.current);
    }
    setToast({ msg, type });
    toastTimer.current = setTimeout(() => setToast(null), 3000);
  };

  useEffect(() => {
    return () => {
      if (toastTimer.current) {
        clearTimeout(toastTimer.current);
      }
    };
  }, []);

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();

    // 🔹 Basic validations
    if (!username.trim()) {
      return showToast("Username is required!", "danger");
    }

    if (!email.includes("@")) {
      return showToast("Invalid email address!", "danger");
    }

    if (password.length < 4) {
      return showToast("Password must be at least 4 characters", "warning");
    }

    if (password !== confirmPassword) {
      return showToast("Passwords do not match!", "danger");
    }

    // 🔹 Save to localStorage (your authContext does this)
    register(email, password);

    showToast("Registered Successfully!", "success");

    // Optionally clear fields
    setUsername("");
    setEmail("");
    setPassword("");
    setConfirmPassword("");

    setTimeout(() => {
      navigate(all_routes.login, { replace: true });
    }, 400);
  };

  const [passwordVisibility, setPasswordVisibility] = useState({
    password: false,
    confirmPassword: false,
  });

  const togglePasswordVisibility = (field: PasswordField) => {
    setPasswordVisibility((prevState) => ({
      ...prevState,
      [field]: !prevState[field],
    }));
  };

  return (
    <>
      {toast && <Toast msg={toast.msg} type={toast.type} />}

      {/* ======================== Start Page Content ========================= */}
      <div className="container-fuild">
        <div className="w-100 overflow-hidden position-relative flex-wrap d-block vh-100">
          <div className="row g-2">
            <div className="col-lg-6 col-md-12 col-sm-12 p-3">
              <div className="row justify-content-center align-items-center overflow-auto flex-wrap auth-vh vh-100">
                <div className="col-xl-8 col-lg-10 col-md-8 col-sm-10 mx-auto">
                  <form onSubmit={handleSubmit}>
                    <div className="d-flex flex-column justify-content-between p-3">
                      <div className="mb-5">
                        <Link to={all_routes.dashboard}>
                          <ImageWithBasePath
                            src="assets/img/logo.svg"
                            className="img-fluid"
                            alt="Logo"
                          />
                        </Link>
                      </div>

                      <div>
                        <div className="mb-4">
                          <h3 className="mb-2">Sign Up</h3>
                          <p className="mb-0">And lets get started with your free trial</p>
                        </div>

                        {/* Username */}
                        <div className="mb-3">
                          <label className="form-label">
                            Username <span className="text-danger">*</span>
                          </label>
                          <input type="text" className="form-control" value={username} onChange={(e) => setUsername(e.target.value)} />
                        </div>

                        {/* Email */}
                        <div className="mb-3">
                          <label className="form-label">
                            Email <span className="text-danger">*</span>
                          </label>
                          <input type="email" className="form-control" value={email} onChange={(e) => setEmail(e.target.value)} />
                        </div>

                        {/* Password */}
                        <div className="mb-3">
                          <label className="form-label">
                            Password <span className="text-danger">*</span>
                          </label>
                          <div className="input-group input-group-flat pass-group">
                            <input type={ passwordVisibility.password ? "text" : "password" } className="form-control pass-input" value={password} onChange={(e) => setPassword(e.target.value)} aria-label="Password" />
                            <span className={`ti toggle-password input-group-text toggle-password ${passwordVisibility.password ? "icon-eye" : "icon-eye-off" }`}onClick={() => togglePasswordVisibility("password")}></span>
                          </div>
                        </div>

                        {/* Confirm Password */}
                        <div className="mb-3">
                          <label className="form-label">
                            Confirm Password{" "}
                            <span className="text-danger">*</span>
                          </label>
                          <div className="input-group input-group-flat pass-group">
                            <input type={ passwordVisibility.confirmPassword ? "text" : "password" } className="form-control pass-input" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} aria-label="Confirm Password" />
                            <span className={`ti toggle-password input-group-text toggle-password ${passwordVisibility.confirmPassword ? "icon-eye" : "icon-eye-off" }`} onClick={() => togglePasswordVisibility("confirmPassword") } ></span>
                          </div>
                        </div>

                        {/* Remember + Forgot */}
                        <div className="d-flex align-items-center justify-content-between mb-4">
                          <div className="form-check form-check-md mb-0">
                            <input className="form-check-input" id="remember_me" type="checkbox" />
                            <label htmlFor="remember_me" className="form-check-label text-dark mt-0" >
                              Remember Me
                            </label>
                          </div>
                          <div className="text-end">
                            <Link to={all_routes.forgotPassword} className="link-primary">
                              Forgot Password?
                            </Link>
                          </div>
                        </div>

                        {/* Submit */}
                        <div className="mb-4">
                          <button
                            type="submit"
                            className="btn btn-primary w-100"
                          >
                            Sign Up
                          </button>
                        </div>

                        {/* Social Buttons */}
                        <div className="login-or position-relative mb-4 text-center">
                          <span className="position-relative bg-white px-2 z-2">
                            or continue with
                          </span>
                        </div>

                        <div className="d-flex align-items-center justify-content-center flex-wrap">
                          <div className="text-center me-2 flex-fill">
                            <Link to="#" className="btn btn-white d-flex align-items-center justify-content-center shadow" >
                              <ImageWithBasePath className="img-fluid me-2" src="assets/img/icons/google.svg" alt="google" />
                              Google
                            </Link>
                          </div>

                          <div className="text-center me-2 flex-fill">
                            <Link to="#" className="btn btn-white d-flex align-items-center justify-content-center shadow" >
                              <ImageWithBasePath className="img-fluid me-2" src="assets/img/icons/fb.svg" alt="facebook" />
                              Facebook
                            </Link>
                          </div>
                        </div>

                        {/* Login Link */}
                        <div className="text-center mt-4">
                          <p className="fw-normal mb-0">
                            Already have an account?{" "}
                            <Link to={all_routes.login} className="link-primary">
                              Sign In
                            </Link>
                          </p>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>

            {/* Right Side */}
            <div className="col-lg-6">
              <div className="position-relative d-lg-flex align-items-center justify-content-center d-none flex-wrap vh-100 p-4 ps-0">
                <div className="w-100 rounded-3 position-relative h-100 bg-primary z-1 overflow-hidden">
                  <ImageWithBasePath src="assets/img/authentication/authentication-bg-01.png" className="img-fluid position-absolute bottom-0 end-0 z-n1 auth-bg-01" alt="bg" />
                  <ImageWithBasePath src="assets/img/authentication/authentication-bg-02.png" className="img-fluid position-absolute top-0 end-0 z-n1 auth-bg-02" alt="bg" />
                  <div className="px-4 rounded-3 h-100 d-flex flex-column align-items-center auth-wrap">
                    <div className="text-center z-2">
                      <h1 className="text-white mb-2">
                        Complete Control of Your Cafe & Restaurant with Ease
                      </h1>
                      <p className="text-white mb-0">
                        From billing to inventory access everything you need in a single powerful dashboard, Analyze sales, track your best-selling dishes.
                      </p>
                    </div>

                    <div className="text-center auth-img position-absolute bottom-0">
                      <ImageWithBasePath src="assets/img/authentication/login.png" className="img-fluid position-relative z-1" alt="user" />
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* End Right Side */}
          </div>
        </div>
      </div>
      {/* ======================== End Page Content ========================= */}
    </>
  );
};

export default Register;

// template/dreamspos-v2.2.4/food-pos-vue-extracted/vue/template/src/views/pages/authentication/register.vue
<template>
    <!-- ========================
        Start Page Content
    ========================= -->

    <div class="container-fuild">

        <!-- Start Content -->
        <div class="w-100 overflow-hidden position-relative flex-wrap d-block vh-100">

            <!-- start row -->
            <div class="row g-2">

                <div class="col-lg-6 col-md-12 col-sm-12 p-3">
                    
                    <!-- start row -->
                    <div class="row justify-content-center align-items-center overflow-auto flex-wrap auth-vh vh-100">
                        
                        <div class="col-xl-8 col-lg-10 col-md-8 col-sm-10 mx-auto">
                            <form @submit.prevent="handleRegister">

                                <div class="d-flex flex-column justify-content-between">
                                    <div class="mb-5">
                                        <a href="#"><img src="@/assets/img/logo.svg" class="img-fluid" alt="Logo"></a>
                                    </div>

                                    <div>
                                        <div class="mb-4">
                                            <h3 class="mb-2">Sign Up</h3>
                                            <p class="mb-0">And lets get started with your free trial</p>
                                        </div>
                                        <div v-if="errorMessage" class="mb-3">
                                            <div class="alert alert-danger border-0 border-danger border-bottom alert-dismissible" role="alert">
                                                <p class="fw-medium mb-0 d-inline-flex align-items-center">
                                                    <i class="icon-circle-x fs-20 me-2"></i>
                                                    {{ errorMessage }}
                                                </p>
                                                <button type="button" class="btn-close text-danger" data-bs-dismiss="alert" aria-label="Close"></button>
                                            </div>
                                        </div>
                                        <div v-if="successMessage" class="mb-3">
                                            <div class="alert alert-success border-0 border-success border-bottom alert-dismissible" role="alert">
                                                <p class="fw-medium mb-0 d-inline-flex align-items-center">
                                                    <i class="icon-circle-check fs-20 me-2"></i>
                                                    {{ successMessage }}
                                                </p>
                                                <button type="button" class="btn-close text-success" data-bs-dismiss="alert" aria-label="Close"></button>
                                            </div>
                                        </div>

                                        <div class="mb-3">
                                            <label class="form-label">Email<span class="text-danger"> *</span></label>
                                            <input type="email" v-model="email" class="form-control">
                                        </div>

                                        <div class="mb-3">
                                            <label class="form-label">Password<span class="text-danger"> *</span></label>
                                            <div class="input-group input-group-flat pass-group">
                                                <input :type="showPassword ? 'text' : 'password'" v-model="password" class="form-control pass-input">
                                                <span class="input-group-text toggle-password" @click="togglePassword">
                                                    <i :class="showPassword ? 'icon-eye' : 'icon-eye-off'"></i>
                                                </span>
                                            </div>
                                        </div>

                                        <div class="mb-3">
                                            <label class="form-label">Confirm Password<span class="text-danger"> *</span></label>
                                            <div class="input-group input-group-flat pass-group">
                                                <input :type="showConfirmPassword ? 'text' : 'password'" v-model="confirmPassword" class="form-control pass-input">
                                                <span class="input-group-text toggle-password" @click="toggleConfirmPassword">
                                                    <i :class="showConfirmPassword ? 'icon-eye' : 'icon-eye-off'"></i>
                                                </span>
                                            </div>
                                        </div>

                                        <div class="form-check form-check-md mb-4">
                                            <input class="form-check-input" id="remember_me" type="checkbox">
                                            <label for="remember_me" class="form-check-label text-dark mt-0">Agree to <a href="#">Terms</a> & <a href="#">Privacy Policy</a></label>
                                        </div>

                                        <div class="mb-4">
                                            <button type="submit" class="btn btn-primary w-100">Sign Up</button>
                                        </div>

                                        <div class="login-or position-relative mb-4 text-center">
                                            <span class="position-relative bg-white px-2 z-2">or continue with</span>
                                        </div>

                                        <div class="d-flex align-items-center justify-content-center flex-wrap">
                                            <div class="text-center me-2 flex-fill">
                                                <a href="#" class="btn btn-white d-flex align-items-center justify-content-center shadow">
                                                    <img class="img-fluid me-2" src="@/assets/img/icons/google.svg" alt="google">Google
                                                </a>
                                            </div>
                                            <div class="text-center me-2 flex-fill">
                                                <a href="#" class="btn btn-white d-flex align-items-center justify-content-center shadow">
                                                    <img class="img-fluid me-2" src="@/assets/img/icons/fb.svg" alt="facebook">Facebook
                                                </a>
                                            </div>
                                        </div>

                                        <div class="text-center mt-4">
                                            <p class="fw-normal mb-0">Already have an account?
                                                <router-link to="/login" class="link-primary"> Sign In</router-link>
                                            </p>
                                        </div>
                                        
                                    </div>                                        
                                </div>

                            </form>
                        </div> <!-- end col -->

                    </div>
                    <!-- end row -->

                </div> <!-- end col -->

                <div class="col-lg-6">
                    <div class="position-relative d-lg-flex align-items-center justify-content-center d-none flex-wrap vh-100 p-4 ps-0">
                        <div class="w-100 rounded-3 position-relative h-100 bg-primary z-1 overflow-hidden">
                            <img src="@/assets/img/authentication/authentication-bg-01.png" class="img-fluid position-absolute bottom-0 end-0 z-n1 auth-bg-01" alt="bg">
                            <img src="@/assets/img/authentication/authentication-bg-02.png" class="img-fluid position-absolute top-0 end-0 z-n1 auth-bg-02" alt="bg">
                            <div class="px-4 rounded-3 h-100 d-flex flex-column align-items-center auth-wrap">
                                <div class="text-center z-2">
                                    <h1 class="text-white mb-2">Complete Control of Your Cafe & Restaurant with Ease</h1>
                                    <p class="text-white mb-0">From billing to inventory access everything you need in a single powerful dashboard, Analyze sales, track your best-selling dishes.</p>
                                </div>
                                <div class="text-center auth-img position-absolute bottom-0">
                                    <img src="@/assets/img/authentication/login.png" class="img-fluid position-relative z-1" alt="user">
                                </div>
                            </div>
                        </div>
                    </div>
                </div> <!-- end col -->

            </div>
            <!-- end row -->

        </div>
        <!-- End Content -->

    </div>

    <!-- ========================
        End Page Content
    ========================= -->
</template>


<script>
import { defineComponent, onMounted, onBeforeUnmount } from "vue";

export default defineComponent({
    data() {
        return {
            name: '',
            email: '',
            password: '',
            confirmPassword: '',
            errorMessage: '',
            successMessage: '',
            isLoading: false,
            showPassword: false,
            showConfirmPassword: false
        };
    },
    methods: {
        togglePassword() {
            this.showPassword = !this.showPassword;
        },
        toggleConfirmPassword() {
            this.showConfirmPassword = !this.showConfirmPassword;
        },
        handleRegister() {
            // Clear previous messages
            this.errorMessage = '';
            this.successMessage = '';
            this.isLoading = true;

            // Basic validation

            if (!this.email.trim()) {
                this.errorMessage = 'Email is required.';
                this.isLoading = false;
                return;
            }

            // Simple email validation
            const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
            if (!emailRegex.test(this.email)) {
                this.errorMessage = 'Please enter a valid email address.';
                this.isLoading = false;
                return;
            }

            if (!this.password) {
                this.errorMessage = 'Password is required.';
                this.isLoading = false;
                return;
            }

            if (this.password.length < 6) {
                this.errorMessage = 'Password must be at least 6 characters long.';
                this.isLoading = false;
                return;
            }

            if (this.password !== this.confirmPassword) {
                this.errorMessage = 'Passwords do not match.';
                this.isLoading = false;
                return;
            }

            // Simulate API delay
            setTimeout(() => {
                // Store registered user credentials in localStorage
                const registeredUsers = JSON.parse(localStorage.getItem('registeredUsers') || '[]');
                
                // Check if email already exists
                const emailExists = registeredUsers.some(user => user.email === this.email.trim());
                if (emailExists) {
                    this.errorMessage = 'This email is already registered. Please use a different email.';
                    this.isLoading = false;
                    return;
                }
                
                // Add new user to registered users
                registeredUsers.push({
                    email: this.email.trim(),
                    password: this.password,
                    name: this.name.trim()
                });
                
                // Save to localStorage
                localStorage.setItem('registeredUsers', JSON.stringify(registeredUsers));
                
                // Fake registration - simulate success
                this.successMessage = 'Verification code sent...';
                this.isLoading = false;
                
                // Redirect to sign in page after 2 seconds with email as query parameter
                // Only pass email if it's valid
                setTimeout(() => {
                if (this.email && this.email.trim()) {
                        this.$router.push({
                        path: '/login',
                        query: { email: this.email.trim() }
                    });
                    } else {
                        this.$router.push('/login');
                    }
                }, 2000);
            }, 1000);
        }
    },
    setup() {
        onMounted(() => {
            document.body.classList.add("bg-white");
            document.documentElement.setAttribute("data-bs-theme", "light");
        });
        onBeforeUnmount(() => {
            document.body.classList.remove("bg-white");
            document.documentElement.removeAttribute("data-bs-theme");
        });
    },
});
</script>
