// template/dreamspos-v2.2.4/nextjs-extracted/nextjs/template/src/components/hrm/attendanceadmin.tsx
"use client";
/* eslint-disable @next/next/no-img-element */

import React from "react";
import { DatePicker } from "antd";
import { attandanceadmindata } from "@/core/json/attendanceadmindata";
import Link from "next/link";
import TooltipIcons from "@/core/common/tooltip-content/tooltipIcons";
import CollapesIcon from "@/core/common/tooltip-content/collapes";
import RefreshIcon from "@/core/common/tooltip-content/refresh";
import { Calendar } from "react-feather";
import AddAttendance from "@/core/modals/hrm/addattendance";
import  Table  from "@/core/common/pagination/datatable";
import EditAttendance from "@/core/modals/hrm/editattendance";

export default function AttendanceAdminComponent  () {
  const dataSource = attandanceadmindata;

  const columns = [
    {
      title: "Employee",
      dataIndex: "Employee",
      render: (text:any, record:any) => (
        <div className="d-flex align-items-center">
          <Link href="#" className="avatar avatar-md me-2">
            <img src={`assets/img/users/${record.image}`} alt="product" />
          </Link>
          <div>
            <h6>
              <Link href="#">{text}</Link>
            </h6>
            <span>{record.Role}</span>
          </div>
        </div>

      ),
      sorter: (a:any, b:any) => a.Employee.length - b.Employee.length,
    },
    {
      title: "Status",
      dataIndex: "Status",
      render: (text:any) => (
        <span className={`badge ${text === 'Present' ? "badge-success" : 'badge-danger'} d-inline-flex align-items-center badge-xs`}>
          <i className="ti ti-point-filled me-1" />
          {text}
        </span>

      ),
      sorter: (a:any, b:any) => a.Status.length - b.Status.length,
    },
    {
      title: "Clock In",
      dataIndex: "Clock_In",
      sorter: (a:any, b:any) => a.Clock_In.length - b.Clock_In.length,
    },
    {
      title: "Clock Out",
      dataIndex: "Clock_Out",
      sorter: (a:any, b:any) => a.Clock_Out.length - b.Clock_Out.length,
    },
    {
      title: "Production",
      dataIndex: "Production",
      sorter: (a:any, b:any) => a.Production.length - b.Production.length,
    },
    {
      title: "Break",
      dataIndex: "Break",
      sorter: (a:any, b:any) => a.Break.length - b.Break.length,
    },
    {
      title: "Overtime",
      dataIndex: "Overtime",
      sorter: (a:any, b:any) => a.Overtime.length - b.Overtime.length,
    },
    {
      title: "Total Hours",
      dataIndex: "Total_Hours",
      sorter: (a:any, b:any) => a.Total_Hours.length - b.Total_Hours.length,
    },
  ];

  return (
    <div>
      <div className="page-wrapper">
        <div className="content">
          <div className="page-header">
            <div className="add-item d-flex">
              <div className="page-title">
                <h4>Attendance</h4>
                <h6>Manage your Attendance</h6>
              </div>
            </div>
            <ul className="table-top-head">
              <TooltipIcons />
              <RefreshIcon />
              <CollapesIcon />
            </ul>
          </div>
          {/* /product list */}
          <div className="card table-list-card">
            <div className="card-header d-flex align-items-center justify-content-between flex-wrap row-gap-3">
              <div className="search-set">
              </div>
              <div className="d-flex table-dropdown my-xl-auto right-content align-items-center flex-wrap row-gap-3">
                <div className="me-2 date-select-small">
                  <div className="input-addon-left position-relative">
                    <DatePicker
                      className="form-control datetimepicker"
                      placeholder="dd/mm/yyyy"
                    />
                    <span className="cus-icon">
                     <Calendar size={14}  />
                    </span>
                  </div>
                </div>
                <div className="dropdown">
                  <Link
                    href="#"
                    className="dropdown-toggle btn btn-white btn-md d-inline-flex align-items-center"
                    data-bs-toggle="dropdown"
                  >
                    Select Status
                  </Link>
                  <ul className="dropdown-menu  dropdown-menu-end p-3">
                    <li>
                      <Link
                        href="#"
                        className="dropdown-item rounded-1"
                      >
                        Present
                      </Link>
                    </li>
                    <li>
                      <Link
                        href="#"
                        className="dropdown-item rounded-1"
                      >
                        Absent
                      </Link>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
            <div className="card-body pb-0">
              <div className="table-responsive">
                <Table columns={columns} dataSource={dataSource} />
              </div>
            </div>
          </div>
          {/* /product list */}
        </div>
        <div className="footer d-sm-flex align-items-center justify-content-between border-top bg-white p-3">
          <p className="mb-0">2014-2025 © DreamsPOS. All Right Reserved</p>
          <p>
            Designed &amp; Developed By{" "}
            <Link href="#" className="text-primary">
              Dreams
            </Link>
          </p>
        </div>
      </div>

      <AddAttendance />
      <EditAttendance />
    </div>
  );
};

// template/dreamspos-v2.2.4/nuxtjs-extracted/nuxtjs/template/app/components/Hrm/AttendanceAdmin.vue
<template>
  <div class="page-wrapper">
    <div class="content">
      <div class="page-header">
        <div class="add-item d-flex">
          <div class="page-title">
            <h4>Attendance</h4>
            <h6>Manage your Attendance</h6>
          </div>
        </div>
        <ul class="table-top-head">
          <li class="me-2">
            <a data-bs-toggle="tooltip" data-bs-placement="top" title="Pdf"
              ><img src="@/assets/img/icons/pdf.svg" alt="img"
            /></a>
          </li>
          <li class="me-2">
            <a data-bs-toggle="tooltip" data-bs-placement="top" title="Excel"
              ><img src="@/assets/img/icons/excel.svg" alt="img"
            /></a>
          </li>
          <li class="me-2">
            <a data-bs-toggle="tooltip" data-bs-placement="top" title="Refresh"
              ><i class="ti ti-refresh"></i
            ></a>
          </li>
          <li class="me-2">
            <a data-bs-toggle="tooltip" data-bs-placement="top" title="Collapse" id="collapse-header" @click="toggleHeader"><i class="ti ti-chevron-up"></i></a>
          </li>
        </ul>
      </div>
      <!-- /product list -->
      <div class="card table-list-card">
        <div
          class="card-header d-flex align-items-center justify-content-between flex-wrap row-gap-3"
        >
          <div class="search-set">
            <div class="search-input">
              <a href="javascript:void(0);" class="btn-searchset"
                ><i class="ti ti-search fs-14 feather-search"></i
              ></a>
              <input
                type="search"
                class="form-control form-control-sm"
                placeholder="Search"
              />
            </div>
          </div>
          <div
            class="d-flex table-dropdown my-xl-auto right-content align-items-center flex-wrap row-gap-3"
          >
            <div class="me-2 date-select-small">
              <div class="input-addon-left position-relative">
                <a-date-picker v-model:value="value1" class="datetimepicker form-control" />
              </div>
            </div>
            <div class="dropdown">
              <a
                href="javascript:void(0);"
                class="dropdown-toggle btn btn-white btn-md d-inline-flex align-items-center"
                data-bs-toggle="dropdown"
              >
                Select Status
              </a>
              <ul class="dropdown-menu dropdown-menu-end p-3">
                <li>
                  <a href="javascript:void(0);" class="dropdown-item rounded-1"
                    >Present</a
                  >
                </li>
                <li>
                  <a href="javascript:void(0);" class="dropdown-item rounded-1">Absent</a>
                </li>
              </ul>
            </div>
          </div>
        </div>
        <div class="card-body pb-0">
          <div class="table-responsive">
            <table class="table datatable">
              <thead class="thead-light">
                <tr>
                  <th>Employee</th>
                  <th>Status</th>
                  <th>Clock In</th>
                  <th>Clock Out</th>
                  <th>Production</th>
                  <th>Break</th>
                  <th>Overtime</th>
                  <th>Total Hours</th>
                </tr>
              </thead>
              <tbody>
                <tr>
                  <td>
                    <div class="d-flex align-items-center">
                      <a href="#" class="avatar avatar-md me-2">
                        <img src="@/assets/img/users/user-01.jpg" alt="product" />
                      </a>
                      <div>
                        <h6><a href="#">Carl Evans</a></h6>
                        <span>Designer</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <span
                      class="badge badge-success d-inline-flex align-items-center badge-xs"
                    >
                      <i class="ti ti-point-filled me-1"></i>Present
                    </span>
                  </td>
                  <td>09:00 AM</td>
                  <td>07:15 PM</td>
                  <td>09h 00m</td>
                  <td>0h 45m</td>
                  <td>0h 20m</td>
                  <td>09h 20m</td>
                </tr>
                <tr>
                  <td>
                    <div class="d-flex align-items-center">
                      <a href="#" class="avatar avatar-md me-2">
                        <img src="@/assets/img/users/user-06.jpg" alt="product" />
                      </a>
                      <div>
                        <h6><a href="#">Minerva Rameriz</a></h6>
                        <span>Administrator</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <span
                      class="badge badge-success d-inline-flex align-items-center badge-xs"
                    >
                      <i class="ti ti-point-filled me-1"></i>Present
                    </span>
                  </td>
                  <td>09:15 AM</td>
                  <td>07:12 PM</td>
                  <td>09h 00m</td>
                  <td>01h 15m</td>
                  <td>0h 12m</td>
                  <td>09h 12m</td>
                </tr>
                <tr>
                  <td>
                    <div class="d-flex align-items-center">
                      <a href="#" class="avatar avatar-md me-2">
                        <img src="@/assets/img/users/user-04.jpg" alt="product" />
                      </a>
                      <div>
                        <h6><a href="#">Robert Lamon</a></h6>
                        <span>Developer</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <span
                      class="badge badge-success d-inline-flex align-items-center badge-xs"
                    >
                      <i class="ti ti-point-filled me-1"></i>Present
                    </span>
                  </td>
                  <td>09:40 AM</td>
                  <td>07:00 PM</td>
                  <td>08h 45m</td>
                  <td>01h 00m</td>
                  <td>00h 00m</td>
                  <td>08h 45m</td>
                </tr>
                <tr>
                  <td>
                    <div class="d-flex align-items-center">
                      <a href="#" class="avatar avatar-md me-2">
                        <img src="@/assets/img/users/user-03.jpg" alt="product" />
                      </a>
                      <div>
                        <h6><a href="#">Patricia Lewis</a></h6>
                        <span>HR Manager</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <span
                      class="badge badge-success d-inline-flex align-items-center badge-xs"
                    >
                      <i class="ti ti-point-filled me-1"></i>Present
                    </span>
                  </td>
                  <td>09:45 AM</td>
                  <td>08:10 PM</td>
                  <td>09h 12m</td>
                  <td>00h 50m</td>
                  <td>00 14m</td>
                  <td>09h 14m</td>
                </tr>
                <tr>
                  <td>
                    <div class="d-flex align-items-center">
                      <a href="#" class="avatar avatar-md me-2">
                        <img src="@/assets/img/users/user-05.jpg" alt="product" />
                      </a>
                      <div>
                        <h6><a href="#">Mark Joslyn</a></h6>
                        <span>Designer</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <span
                      class="badge badge-danger d-inline-flex align-items-center badge-xs"
                    >
                      <i class="ti ti-point-filled me-1"></i>Absent
                    </span>
                  </td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>
                    <div class="d-flex align-items-center">
                      <a href="#" class="avatar avatar-md me-2">
                        <img src="@/assets/img/users/user-05.jpg" alt="product" />
                      </a>
                      <div>
                        <h6><a href="#">Marsha Betts</a></h6>
                        <span>Developer</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <span
                      class="badge badge-success d-inline-flex align-items-center badge-xs"
                    >
                      <i class="ti ti-point-filled me-1"></i>Present
                    </span>
                  </td>
                  <td>09:17 AM</td>
                  <td>07:34 PM</td>
                  <td>09h 26m</td>
                  <td>01h 20m</td>
                  <td>00h 26m</td>
                  <td>09h 26m</td>
                </tr>
                <tr>
                  <td>
                    <div class="d-flex align-items-center">
                      <a href="#" class="avatar avatar-md me-2">
                        <img src="@/assets/img/users/user-28.jpg" alt="product" />
                      </a>
                      <div>
                        <h6><a href="#">Daniel Jude</a></h6>
                        <span>Administrator</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <span
                      class="badge badge-danger d-inline-flex align-items-center badge-xs"
                    >
                      <i class="ti ti-point-filled me-1"></i>Absent
                    </span>
                  </td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                  <td>-</td>
                </tr>
                <tr>
                  <td>
                    <div class="d-flex align-items-center">
                      <a href="#" class="avatar avatar-md me-2">
                        <img src="@/assets/img/users/user-12.jpg" alt="product" />
                      </a>
                      <div>
                        <h6><a href="#">Emma Bates</a></h6>
                        <span>HR Assistant</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <span
                      class="badge badge-success d-inline-flex align-items-center badge-xs"
                    >
                      <i class="ti ti-point-filled me-1"></i>Present
                    </span>
                  </td>
                  <td>09:42 AM</td>
                  <td>07:20 PM</td>
                  <td>09h 17m</td>
                  <td>01h 00m</td>
                  <td>00h 17m</td>
                  <td>09h 17m</td>
                </tr>
                <tr>
                  <td>
                    <div class="d-flex align-items-center">
                      <a href="#" class="avatar avatar-md me-2">
                        <img src="@/assets/img/users/user-30.jpg" alt="product" />
                      </a>
                      <div>
                        <h6><a href="#">Richard Fralick </a></h6>
                        <span>Designer</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <span
                      class="badge badge-success d-inline-flex align-items-center badge-xs"
                    >
                      <i class="ti ti-point-filled me-1"></i>Present
                    </span>
                  </td>
                  <td>09:18 AM</td>
                  <td>07:11 PM</td>
                  <td>09h 32m</td>
                  <td>01h 15m</td>
                  <td>00h 32m</td>
                  <td>09h 32m</td>
                </tr>
                <tr>
                  <td>
                    <div class="d-flex align-items-center">
                      <a href="#" class="avatar avatar-md me-2">
                        <img src="@/assets/img/users/user-26.jpg" alt="product" />
                      </a>
                      <div>
                        <h6><a href="#">Michelle Robison</a></h6>
                        <span>HR Manager</span>
                      </div>
                    </div>
                  </td>
                  <td>
                    <span
                      class="badge badge-success d-inline-flex align-items-center badge-xs"
                    >
                      <i class="ti ti-point-filled me-1"></i>Present
                    </span>
                  </td>
                  <td>09:30 AM</td>
                  <td>08:10 PM</td>
                  <td>09h 00m</td>
                  <td>00h 34m</td>
                  <td>00h 20m</td>
                  <td>09h 20m</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>
      <!-- /product list -->
    </div>
    <div
      class="footer d-sm-flex align-items-center justify-content-between border-top bg-white p-3"
    >
      <p class="mb-0">
        {{ new Date().getFullYear() }} &copy; DreamsPOS. All Right Reserved
      </p>
      <p>
        Designed &amp; Developed By
        <a href="javascript:void(0);" class="text-primary">Dreams</a>
      </p>
    </div>
  </div>
</template>
<script>
import { ref } from "vue";
const value1 = ref();
export default {
  data() {
    return {
      value1,
    };
  },
  methods: {
    toggleHeader() {
      document.getElementById("collapse-header").classList.toggle("active");
      document.body.classList.toggle("header-collapse");
    },
  },
};
</script>
