// template/dreamspos-v2.2.4/food-pos-nextjs-extracted/nextjs/template/src/components/authentication/login/login.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";

import Toast from "@/core/common/toast/toast";
import { useAuth } from "../auth-context/authContext";
import { all_routes } from "../../../routes/all_routes";
import ImageWithBasePath from "@/core/common/image-with-base-path";

type PasswordField = "password" | "confirmPassword";

const Login = () => {
  const router = useRouter();
  const { login } = useAuth();

  // Form state
  const [email, setEmail] = useState("admin@gmail.com");
  const [password, setPassword] = useState("123456");

  // Toast state
  const [toast, setToast] = useState<{
    msg: string;
    type: "success" | "danger" | "warning" | "info";
  } | null>(null);

  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const showToast = (
    message: string,
    type: "success" | "danger" | "warning" | "info"
  ) => {
    if (toastTimer.current) clearTimeout(toastTimer.current);

    setToast({ msg: message, type });
    toastTimer.current = setTimeout(() => {
      setToast(null);
    }, 3000);
  };

  useEffect(() => {
    return () => {
      if (toastTimer.current) clearTimeout(toastTimer.current);
    };
  }, []);

  // Handle Login
  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();

    if (!email.trim() || !password) {
      showToast("Please fill all fields!", "danger");
      return;
    }

    const result = login(email.trim(), password);

    if (!result.ok) {
      showToast(result.msg ?? "Invalid email or password", "danger");
      return;
    }

    showToast("Login successful!", "success");

    router.push(all_routes.dashboard);
  };

  // Password visibility
  const [passwordVisibility, setPasswordVisibility] = useState({
    password: false,
    confirmPassword: false,
  });

  const togglePasswordVisibility = (field: PasswordField) => {
    setPasswordVisibility((prev) => ({
      ...prev,
      [field]: !prev[field],
    }));
  };

  return (
    <>
      {/* Toast */}
      {toast && <Toast msg={toast.msg} type={toast.type} />}

      {/* Begin Wrapper */}
      <div className="main-wrapper">
        {/* ========================
          Start Page Content
        ========================= */}
        <div className="container-fuild">
          {/* Start Content */}
          <div className="w-100 overflow-hidden position-relative flex-wrap d-block vh-100">
            {/* start row */}
            <div className="row g-2">
              <div className="col-lg-6 col-md-12 col-sm-12 p-3">
                {/* start row */}
                <div className="row justify-content-center align-items-center overflow-auto flex-wrap auth-vh vh-100">
                  <div className="col-xl-8 col-lg-10 col-md-8 col-sm-10 mx-auto">
                    <form onSubmit={handleLogin}>
                      <div className="d-flex flex-column justify-content-between">
                        <div className="mb-5">
                          <Link href="/">
                            <ImageWithBasePath
                              src="assets/img/logo.svg"
                              className="img-fluid"
                              alt="Logo"
                            />
                          </Link>
                        </div>
                        <div>
                          <div className="mb-4">
                            <h3 className="mb-2">Hi, Welcome Back !!!</h3>
                            <p className="mb-0">
                              Please enter your credentials to sign in!
                            </p>
                          </div>
                          <div className="mb-3">
                            <label className="form-label">
                              Email<span className="text-danger"> *</span>
                            </label>
                            <input
                              type="email"
                              className="form-control"
                              value={email}
                              onChange={(e) => setEmail(e.target.value)}
                              placeholder="name@example.com"
                            />
                          </div>
                          <div className="mb-3">
                            <label className="form-label">
                              Password<span className="text-danger"> *</span>
                            </label>
                            <div className="input-group input-group-flat pass-group">
                              <input
                                type={
                                  passwordVisibility.password
                                    ? "text"
                                    : "password"
                                }
                                className="form-control pass-input"
                                value={password}
                                onChange={(e) => setPassword(e.target.value)}
                              />
                              <span
                                className="input-group-text toggle-password"
                                onClick={() => togglePasswordVisibility("password")}
                              >
                                <i
                                  className={
                                    passwordVisibility.password
                                      ? "icon-eye"
                                      : "icon-eye-off"
                                  }
                                />
                              </span>
                            </div>
                          </div>
                          <div className="d-flex align-items-center justify-content-between mb-4">
                            <div className="d-flex align-items-center">
                              <div className="form-check form-check-md mb-0">
                                <input
                                  className="form-check-input"
                                  id="remember_me"
                                  type="checkbox"
                                />
                                <label
                                  htmlFor="remember_me"
                                  className="form-check-label text-dark mt-0"
                                >
                                  Remember Me
                                </label>
                              </div>
                            </div>
                            <div className="text-end">
                              <Link
                                href={all_routes.forgotPassword}
                                className="link-primary"
                              >
                                Forgot Password?
                              </Link>
                            </div>
                          </div>
                          <div className="mb-4">
                            <button
                              type="submit"
                              className="btn btn-primary w-100"
                            >
                              Sign In
                            </button>
                          </div>
                          <div className="login-or position-relative mb-4 text-center">
                            <span className="position-relative bg-white px-2 z-2">
                              or continue with
                            </span>
                          </div>
                          <div className="d-flex align-items-center justify-content-center flex-wrap">
                            <div className="text-center me-2 flex-fill">
                              <Link
                                href="#"
                                className="btn btn-white d-flex align-items-center justify-content-center shadow"
                              >
                                <ImageWithBasePath
                                  className="img-fluid me-2"
                                  src="assets/img/icons/google.svg"
                                  alt="google"
                                />
                                Google
                              </Link>
                            </div>
                            <div className="text-center me-2 flex-fill">
                              <Link
                                href="#"
                                className="btn btn-white d-flex align-items-center justify-content-center shadow"
                              >
                                <ImageWithBasePath
                                  className="img-fluid me-2"
                                  src="assets/img/icons/fb.svg"
                                  alt="facebook"
                                />
                                Facebook
                              </Link>
                            </div>
                          </div>
                          <div className="text-center mt-4">
                            <p className="fw-normal mb-0">
                              Don&apos;t have an account?
                              <Link
                                href={all_routes.register}
                                className="link-primary"
                              >
                                {" "}
                                Sign Up
                              </Link>
                            </p>
                          </div>
                        </div>
                      </div>
                    </form>
                  </div>
                  {/* end col */}
                </div>
                {/* end row */}
              </div>
              {/* end col */}
              <div className="col-lg-6">
                <div className="position-relative d-lg-flex align-items-center justify-content-center d-none flex-wrap vh-100 p-4 ps-0">
                  <div className="w-100 rounded-3 position-relative h-100 bg-primary z-1 overflow-hidden">
                    <ImageWithBasePath
                      src="assets/img/authentication/authentication-bg-01.png"
                      className="img-fluid position-absolute end-0 z-n1 auth-bg-01"
                      alt="bg"
                    />
                    <ImageWithBasePath
                      src="assets/img/authentication/authentication-bg-02.png"
                      className="img-fluid position-absolute top-0 end-0 z-n1 auth-bg-02"
                      alt="bg"
                    />
                    <div className="px-4 rounded-3 h-100 d-flex flex-column align-items-center auth-wrap">
                      <div className="text-center z-2">
                        <h1 className="text-white mb-2">
                          Complete Control of Your Cafe &amp; Restaurant with
                          Ease
                        </h1>
                        <p className="text-white mb-0">
                          From billing to inventory access everything you need
                          in a single powerful dashboard, Analyze sales, track
                          your best-selling dishes.
                        </p>
                      </div>
                      <div className="text-center auth-img position-absolute bottom-0">
                        <ImageWithBasePath
                          src="assets/img/authentication/login.png"
                          className="img-fluid position-relative z-1"
                          alt="user"
                        />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              {/* end col */}
            </div>
            {/* end row */}
          </div>
          {/* End Content */}
        </div>
        {/* ========================
          End Page Content
        ========================= */}
      </div>
      {/* End Wrapper */}
    </>
  );
};

export default Login;

// template/dreamspos-v2.2.4/nuxtjs-extracted/nuxtjs/template/app/components/Modules/Authentication/login/login.vue
<template>
    <div class="main-wrapper">
      <div class="account-content">
        <div class="login-wrapper bg-img">
          <div class="login-content authent-content">
            <form @submit.prevent="handleLogin">
              <div class="login-userset">
                <div class="login-logo logo-normal">
                  <img src="@/assets/img/logo.svg" alt="img">
                </div>
                <NuxtLink to="/dashboard/admin-dashboard" class="login-logo logo-white">
                  <img src="@/assets/img/logo-white.svg" alt="Img" />
                </NuxtLink>
                <div class="login-userheading">
                  <h3>Sign In</h3>
                  <h4 class="fs-16">Access the Dreamspos panel using your email and passcode.</h4>
                </div>
                <div v-if="errorMessage" class="mb-3">
                  <div class="alert alert-danger" role="alert">
                    {{ errorMessage }}
                  </div>
                </div>
                <div class="mb-3">
                  <label class="form-label">Email <span class="text-danger"> *</span></label>
                  <div class="input-group">
                    <input type="text" v-model="email" class="form-control border-end-0">
                    <span class="input-group-text border-start-0">
                      <i class="ti ti-mail"></i>
                    </span>
                  </div>
                </div>
                <div class="mb-3">
                  <label class="form-label">Password <span class="text-danger"> *</span></label>
                  <div class="pass-group">
                    <input :type="showPassword ? 'text' : 'password'" v-model="password" class="pass-input form-control">
                    <span class="ti toggle-password" :class="showPassword ? 'ti-eye text-gray-9' : 'ti-eye-off text-gray-9'" @click="togglePassword"></span>
                  </div>
                </div>
                <div class="form-login authentication-check">
                  <div class="row">
                    <div class="col-12 d-flex align-items-center justify-content-between">
                      <div class="custom-control custom-checkbox">
                        <label class="checkboxs ps-4 mb-0 pb-0 line-height-1 fs-16 text-gray-6">
                          <input type="checkbox" v-model="rememberMe" class="form-control">
                          <span class="checkmarks"></span>Remember me
                        </label>
                      </div>
                      <div class="text-end">
                        <NuxtLink class="text-orange fs-16 fw-medium" to="/forgot-password">Forgot Password?</NuxtLink>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="form-login">
                  <button type="submit" class="btn btn-primary w-100" :disabled="isLoading">
                    <span v-if="isLoading">Signing In...</span>
                    <span v-else>Sign In</span>
                  </button>
                </div>
                <div class="signinform">
                  <h4>New on our platform?<NuxtLink to="/register" class="hover-a"> Create an account</NuxtLink></h4>
                </div>
                <div class="form-setlogin or-text">
                  <h4>OR</h4>
                </div>
                <div class="mt-2">
                  <div class="d-flex align-items-center justify-content-center flex-wrap">
                    <div class="text-center me-2 flex-fill">
                      <a href="javascript:void(0);"
                        class="br-10 p-2 btn btn-info d-flex align-items-center justify-content-center">
                        <img class="img-fluid m-1" src="@/assets/img/icons/facebook-logo.svg" alt="Facebook">
                      </a>
                    </div>
                    <div class="text-center me-2 flex-fill">
                      <a href="javascript:void(0);"
                        class="btn btn-white br-10 p-2  border d-flex align-items-center justify-content-center">
                        <img class="img-fluid m-1" src="@/assets/img/icons/google-logo.svg" alt="Facebook">
                      </a>
                    </div>
                    <div class="text-center flex-fill">
                      <a href="javascript:void(0);"
                        class="bg-dark br-10 p-2 btn btn-dark d-flex align-items-center justify-content-center">
                        <img class="img-fluid m-1" src="@/assets/img/icons/apple-logo.svg" alt="Apple">
                      </a>
                    </div>
                  </div>
                </div>
                <div class="my-4 d-flex justify-content-center align-items-center copyright-text">
                  <p>Copyright &copy; 2025 DreamsPOS</p>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </div>
  </template>
  
  <script>
  export default {
    name: 'SignIn',
    data() {
      return {
        email: 'admin@example.com',
        password: '123456',
        rememberMe: false,
        errorMessage: '',
        isLoading: false,
        showPassword: false
      };
    },
    mounted() {
      // Check if email is passed as query parameter from registration
      if (this.$route.query.email) {
        this.email = this.$route.query.email;
      }
    },
    methods: {
      togglePassword() {
        this.showPassword = !this.showPassword;
      },
      handleLogin() {
        // Clear previous error
        this.errorMessage = '';
        this.isLoading = true;
  
        // Simulate API delay
        setTimeout(() => {
          let isAuthenticated = false;
          
          // Check default admin credentials
          if (this.email === 'admin@example.com' && this.password === '123456') {
            isAuthenticated = true;
          } else {
            // Check registered users from localStorage
            const registeredUsers = JSON.parse(localStorage.getItem('registeredUsers') || '[]');
            const user = registeredUsers.find(
              user => user.email === this.email.trim() && user.password === this.password
            );
            
            if (user) {
              isAuthenticated = true;
            }
          }
          
          
          if (isAuthenticated) {
            // Success - redirect to dashboard
            this.$router.push('/dashboard/admin-dashboard');
          } else {
            // Show error message
            this.errorMessage = 'Invalid email or password. Please try again.';
            this.isLoading = false;
          }
        }, 1000);
      }
    }
  };
  </script>
