// template/dreamspos-v2.2.4/food-pos-vue-extracted/vue/template/src/views/pages/settings-module/store-settings.vue
<template>
    <!-- ========================
        Start Page Content
    ========================= -->
        
    <div class="page-wrapper">

        <!-- Start Content -->
        <div class="content">

            <!-- Page Header -->
            <div class="d-flex align-items-sm-center flex-sm-row flex-column gap-3 mb-4">
                <div class="flex-grow-1">
                    <h3 class="mb-0">Store Settings <a href="#" class="btn btn-icon btn-sm btn-white rounded-circle ms-2"><i class="icon-refresh-ccw"></i></a></h3>
                </div>
            </div>
            <!-- End Page Header -->

            <div>
                <!-- card start -->
                <div class="card">
                    <div class="card-body">
                        <form action="#">

                            <!-- start row -->
                            <div class="row">

                                <div class="col-xl-12">
                                    <div class="mb-3 d-flex align-items-center flex-wrap gap-3">
                                        <div class="avatar avatar-3xl border bg-light">
                                            <i class="icon-images fs-28 text-dark"></i>
                                        </div>
                                        <div>
                                            <label class="form-label mb-1">Upload Store Image</label>
                                            <p class="fs-13 mb-3">Image should be with in 5 MB</p>
                                            <div class="d-flex align-items-center">
                                                <div class="btn btn-icon btn-sm btn-white rounded-circle position-relative me-2">
                                                    <input type="file" class="form-control position-absolute w-100 h-100 top-0 start-0 opacity-0">
                                                    <i class="icon-pencil-line"></i>
                                                </div>
                                                <a href="#" class="btn btn-icon btn-sm btn-white rounded-circle text-danger"><i class="icon-trash-2"></i></a>
                                            </div>
                                        </div>                                        
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-12">
                                    <div class="mb-3">
                                        <label class="form-label">Store Name<span class="text-danger ms-1">*</span></label>
                                        <input type="text" class="form-control">
                                    </div>
                                </div> <!-- end col -->
                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label">Address 1<span class="text-danger ms-1">*</span></label>
                                        <input type="text" class="form-control">
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label">Address 2</label>
                                        <input type="text" class="form-control">
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-3">
                                    <div class="mb-3">
                                        <label class="form-label">Country<span class="text-danger ms-1">*</span></label>
                                        <vue-select 
                                            :options="Country"
                                            v-model="selected"
                                            placeholder="Select"
                                        />
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-3">
                                    <div class="mb-3">
                                        <label class="form-label">State<span class="text-danger ms-1">*</span></label>
                                        <vue-select 
                                            :options="State"
                                            v-model="selectedOne"
                                            placeholder="Select"
                                        />
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-3">
                                    <div class="mb-3">
                                        <label class="form-label">City<span class="text-danger ms-1">*</span></label>
                                        <vue-select 
                                            :options="City"
                                            v-model="selectedTwo"
                                            placeholder="Select"
                                        />
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-3">
                                    <div class="mb-3">
                                        <label class="form-label">Pincode<span class="text-danger ms-1">*</span></label>
                                        <input type="text" class="form-control">
                                    </div>
                                </div> <!-- end col -->
                                

                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label">Email<span class="text-danger ms-1">*</span></label>
                                        <input type="email" class="form-control">
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <label class="form-label">Phone<span class="text-danger ms-1">*</span></label>
                                        <input type="tel" class="form-control" id="phone" name="phone">
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-12">
                                    <div class="mb-3">
                                        <label class="form-label">Currency<span class="text-danger ms-1">*</span></label>
                                        <vue-select 
                                            :options="Currency"
                                            v-model="selectedThree"
                                            placeholder="Select"
                                        />
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-6">
                                    <div class="mb-3">
                                        <div class="form-check form-switch mb-3">
                                            <input class="form-check-input" type="checkbox" role="switch" id="switchCheckChecked" checked>
                                            <label class="form-check-label" for="switchCheckChecked">Enable QR Menu</label>
                                        </div>
                                        <div class="form-check form-switch mb-3">
                                            <input class="form-check-input" type="checkbox" role="switch" id="switchCheckChecked1" checked>
                                            <label class="form-check-label" for="switchCheckChecked1">Enable Take Away</label>
                                        </div>
                                        <div class="form-check form-switch mb-3">
                                            <input class="form-check-input" type="checkbox" role="switch" id="switchCheckChecked2" checked>
                                            <label class="form-check-label" for="switchCheckChecked2">Enable Dine In</label>
                                        </div>
                                        <div class="form-check form-switch mb-0">
                                            <input class="form-check-input" type="checkbox" role="switch" id="switchCheckChecked3">
                                            <label class="form-check-label" for="switchCheckChecked3">Enable Reservation</label>
                                        </div>
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-6">
                                    <div class="mb-0">
                                        <div class="form-check form-switch mb-3">
                                            <input class="form-check-input" type="checkbox" role="switch" id="switchCheckChecked4" checked>
                                            <label class="form-check-label" for="switchCheckChecked4">Enable Order Via QR Menu</label>
                                        </div>
                                        <div class="form-check form-switch mb-3">
                                            <input class="form-check-input" type="checkbox" role="switch" id="switchCheckChecked5" checked>
                                            <label class="form-check-label" for="switchCheckChecked5">Enable Delivery</label>
                                        </div>
                                        <div class="form-check form-switch mb-0">
                                            <input class="form-check-input" type="checkbox" role="switch" id="switchCheckChecked6" checked>
                                            <label class="form-check-label" for="switchCheckChecked6">Enable Table</label>
                                        </div>
                                    </div>
                                </div> <!-- end col -->

                            </div>
                            <!-- end row -->

                            
                            <div class="d-flex align-items-center justify-content-end flex-wrap row-gap-2 border-top mt-2 pt-4">
                                <button type="button" class="btn btn-light me-2">Cancel</button>
                                <button type="submit" class="btn btn-primary">Save Changes</button>
                            </div>

                        </form>
                    </div> <!-- end card body -->

                </div>
                <!-- card start -->

                
            </div>
                            
        </div>
        <!-- End Content -->  

    </div>

    <!-- ========================
        End Page Content
    ========================= -->
</template>

<script>
export default {
    data(){
        return {
            selected: [],
            selectedOne: [],
            selectedTwo: [],
            selectedThree: [],
            Country: [
                { label: "Select", value: "Select" },
                { label: "United States", value: "United States" },
                { label: "Canada", value: "Canada" },
                { label: "Germany", value: "Germany" },
                { label: "France", value: "France" },
            ],
            State: [
                { label: "Select", value: "Select" },
                { label: "California", value: "California" },
                { label: "New York", value: "New York" },
                { label: "Texas", value: "Texas" },
                { label: "Florida", value: "Florida" },
            ],
            City: [
                { label: "Select", value: "Select" },
                { label: "Los Angeles", value: "Los Angeles" },
                { label: "San Diego", value: "San Diego" },
                { label: "Fresno", value: "Fresno" },
                { label: "San Francisco", value: "San Francisco" },
            ],
            Currency: [
                { label: "Select", value: "Select" },
                { label: "USD", value: "USD" },
                { label: "AED", value: "AED" },
                { label: "INR", value: "INR" },
            ],
        }
    }
}
</script>

// frontend/src/pages-template/settings/storeSettings.tsx
﻿
import { City, Country, Currency, State } from "../../core/json/selectOption";
import CommonSelect from "../../components-template/common-select/commonSelect";
import { Link } from "react-router-dom";


const StoreSettings = () => {

    return (
        <>
            {/* ========================
			Start Page Content
		    ========================= */}
            <div className="page-wrapper">
                {/* Start Content */}
                <div className="content">
                    {/* Page Header */}
                    <div className="d-flex align-items-sm-center flex-sm-row flex-column gap-3 mb-4">
                        <div className="flex-grow-1">
                            <h3 className="mb-0">
                                Store Settings{" "}
                                <Link
                                    to="#"
                                    className="btn btn-icon btn-sm btn-white rounded-circle ms-2"
                                >
                                    <i className="icon-refresh-ccw" />
                                </Link>
                            </h3>
                        </div>
                    </div>
                    {/* End Page Header */}
                    <div>
                        {/* card start */}
                        <div className="card">
                            <div className="card-body">
                                <form>
                                    {/* start row */}
                                    <div className="row">
                                        <div className="col-xl-12">
                                            <div className="mb-3 d-flex align-items-center flex-wrap gap-3">
                                                <div className="avatar avatar-3xl border bg-light">
                                                    <i className="icon-images fs-28 text-dark" />
                                                </div>
                                                <div>
                                                    <label className="form-label mb-1">
                                                        Upload Store Image
                                                    </label>
                                                    <p className="fs-13 mb-3">Image should be with in 5 MB</p>
                                                    <div className="d-flex align-items-center">
                                                        <div className="btn btn-icon btn-sm btn-white rounded-circle position-relative me-2">
                                                            <input
                                                                type="file"
                                                                className="form-control position-absolute w-100 h-100 top-0 start-0 opacity-0"
                                                            />
                                                            <i className="icon-pencil-line" />
                                                        </div>
                                                        <Link
                                                            to="#"
                                                            className="btn btn-icon btn-sm btn-white rounded-circle text-danger"
                                                        >
                                                            <i className="icon-trash-2" />
                                                        </Link>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-12">
                                            <div className="mb-3">
                                                <label className="form-label">
                                                    Store Name<span className="text-danger ms-1">*</span>
                                                </label>
                                                <input type="text" className="form-control" />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-6">
                                            <div className="mb-3">
                                                <label className="form-label">
                                                    Address 1<span className="text-danger ms-1">*</span>
                                                </label>
                                                <input type="text" className="form-control" />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-6">
                                            <div className="mb-3">
                                                <label className="form-label">Address 2</label>
                                                <input type="text" className="form-control" />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-3">
                                            <div className="mb-3">
                                                <label className="form-label">
                                                    Country<span className="text-danger ms-1">*</span>
                                                </label>
                                                <CommonSelect
                                                    options={Country}
                                                    className="select"
                                                    defaultValue={Country[0]}
                                                />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-3">
                                            <div className="mb-3">
                                                <label className="form-label">
                                                    State<span className="text-danger ms-1">*</span>
                                                </label>
                                                <CommonSelect
                                                    options={State}
                                                    className="select"
                                                    defaultValue={State[0]}
                                                />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-3">
                                            <div className="mb-3">
                                                <label className="form-label">
                                                    City<span className="text-danger ms-1">*</span>
                                                </label>
                                                <CommonSelect
                                                    options={City}
                                                    className="select"
                                                    defaultValue={City[0]}
                                                />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-3">
                                            <div className="mb-3">
                                                <label className="form-label">
                                                    Pincode<span className="text-danger ms-1">*</span>
                                                </label>
                                                <input type="text" className="form-control" />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-6">
                                            <div className="mb-3">
                                                <label className="form-label">
                                                    Email<span className="text-danger ms-1">*</span>
                                                </label>
                                                <input type="email" className="form-control" />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-6">
                                            <div className="mb-3">
                                                <label className="form-label">
                                                    Phone<span className="text-danger ms-1">*</span>
                                                </label>
                                                <input
                                                    type="tel"
                                                    className="form-control"
                                                    id="phone"
                                                    name="phone"
                                                />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-12">
                                            <div className="mb-3">
                                                <label className="form-label">
                                                    Currency<span className="text-danger ms-1">*</span>
                                                </label>
                                                <CommonSelect
                                                    options={Currency}
                                                    className="select"
                                                    defaultValue={Currency[0]}
                                                />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-6">
                                            <div className="mb-3">
                                                <div className="form-check form-switch mb-3">
                                                    <input
                                                        className="form-check-input"
                                                        type="checkbox"
                                                        role="switch"
                                                        id="switchCheckChecked"
                                                        defaultChecked
                                                    />
                                                    <label
                                                        className="form-check-label"
                                                        htmlFor="switchCheckChecked"
                                                    >
                                                        Enable QR Menu
                                                    </label>
                                                </div>
                                                <div className="form-check form-switch mb-3">
                                                    <input
                                                        className="form-check-input"
                                                        type="checkbox"
                                                        role="switch"
                                                        id="switchCheckChecked1"
                                                        defaultChecked
                                                    />
                                                    <label
                                                        className="form-check-label"
                                                        htmlFor="switchCheckChecked1"
                                                    >
                                                        Enable Take Away
                                                    </label>
                                                </div>
                                                <div className="form-check form-switch mb-3">
                                                    <input
                                                        className="form-check-input"
                                                        type="checkbox"
                                                        role="switch"
                                                        id="switchCheckChecked2"
                                                        defaultChecked
                                                    />
                                                    <label
                                                        className="form-check-label"
                                                        htmlFor="switchCheckChecked2"
                                                    >
                                                        Enable Dine In
                                                    </label>
                                                </div>
                                                <div className="form-check form-switch mb-0">
                                                    <input
                                                        className="form-check-input"
                                                        type="checkbox"
                                                        role="switch"
                                                        id="switchCheckChecked3"
                                                    />
                                                    <label
                                                        className="form-check-label"
                                                        htmlFor="switchCheckChecked3"
                                                    >
                                                        Enable Reservation
                                                    </label>
                                                </div>
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-6">
                                            <div className="mb-0">
                                                <div className="form-check form-switch mb-3">
                                                    <input
                                                        className="form-check-input"
                                                        type="checkbox"
                                                        role="switch"
                                                        id="switchCheckChecked4"
                                                        defaultChecked
                                                    />
                                                    <label
                                                        className="form-check-label"
                                                        htmlFor="switchCheckChecked4"
                                                    >
                                                        Enable Order Via QR Menu
                                                    </label>
                                                </div>
                                                <div className="form-check form-switch mb-3">
                                                    <input
                                                        className="form-check-input"
                                                        type="checkbox"
                                                        role="switch"
                                                        id="switchCheckChecked5"
                                                        defaultChecked
                                                    />
                                                    <label
                                                        className="form-check-label"
                                                        htmlFor="switchCheckChecked5"
                                                    >
                                                        Enable Delivery
                                                    </label>
                                                </div>
                                                <div className="form-check form-switch mb-0">
                                                    <input
                                                        className="form-check-input"
                                                        type="checkbox"
                                                        role="switch"
                                                        id="switchCheckChecked6"
                                                        defaultChecked
                                                    />
                                                    <label
                                                        className="form-check-label"
                                                        htmlFor="switchCheckChecked6"
                                                    >
                                                        Enable Table
                                                    </label>
                                                </div>
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                    </div>
                                    <div className="d-flex align-items-center justify-content-end flex-wrap row-gap-2 border-top mt-2 pt-4">
                            <button type="button" className="btn btn-light me-2">
                                Cancel
                            </button>
                            <button type="submit" className="btn btn-primary">
                                Save Changes
                            </button>
                        </div>
                                    {/* end row */}
                                </form>
                            </div>{" "}
                            {/* end card body */}
                        </div>
                        {/* card start */}
                        
                    </div>
                </div>
                {/* End Content */}
            </div>
            {/* ========================
			End Page Content
		    ========================= */}
        </>


    )
}

export default StoreSettings
