// template/dreamspos-v2.2.4/food-pos-vue-extracted/vue/template/src/views/pages/authentication/login.vue
<template>
    <!-- ========================
        Start Page Content
    ========================= -->

    <div class="container-fuild">

        <!-- Start Content -->
        <div class="w-100 overflow-hidden position-relative flex-wrap d-block vh-100">

            <!-- start row -->
            <div class="row g-2">

                <div class="col-lg-6 col-md-12 col-sm-12 p-3">
                    
                    <!-- start row -->
                    <div class="row justify-content-center align-items-center overflow-auto flex-wrap auth-vh vh-100">
                        
                        <div class="col-xl-8 col-lg-10 col-md-8 col-sm-10 mx-auto">
                            <form @submit.prevent="handleLogin">
                                
                                <div v-if="errorMessage" class="mb-3">
                                    <div class="alert alert-danger border-0 border-danger border-bottom alert-dismissible" role="alert">
                                        <p class="fw-medium mb-0 d-inline-flex align-items-center">
                                            <i class="icon-circle-x fs-20 me-2"></i>
                                            {{ errorMessage }}
                                        </p>
                                        <a href="#" class="ms-3 top-50 translate-middle-y link-danger" data-bs-dismiss="alert" aria-label="Close"> 
                                            <i class="icon-x"></i> 
                                        </a>
                                    </div>
                                </div>

                                <div class="d-flex flex-column justify-content-between">
                                    <div class="mb-5">
                                        <a href="#"><img src="@/assets/img/logo.svg" class="img-fluid" alt="Logo"></a>
                                    </div>

                                    <div>
                                        <div class="mb-4">
                                            <h3 class="mb-2">Hi, Welcome Back !!!</h3>
                                            <p class="mb-0">Please enter your credentials to sign in!</p>
                                        </div>
                                        <div class="mb-3">
                                            <label class="form-label">Email<span class="text-danger"> *</span></label>
                                            <input type="email" v-model="email" class="form-control">
                                        </div>

                                        <div class="mb-3">
                                            <label class="form-label">Password<span class="text-danger"> *</span></label>
                                            <div class="input-group input-group-flat pass-group">
                                                <input :type="showPassword ? 'text' : 'password'" v-model="password" class="form-control pass-input">
                                                <span class="input-group-text toggle-password" @click="togglePassword">
                                                    <i :class="showPassword ? 'icon-eye' : 'icon-eye-off'"></i>
                                                </span>
                                            </div>
                                        </div>

                                        <div class="d-flex align-items-center justify-content-between mb-4">
                                            <div class="d-flex align-items-center">
                                                <div class="form-check form-check-md mb-0">
                                                    <input class="form-check-input" v-model="rememberMe" id="remember_me" type="checkbox">
                                                    <label for="remember_me" class="form-check-label text-dark mt-0">Remember Me</label>
                                                </div>
                                            </div>
                                            <div class="text-end">
                                                <router-link to="/forgot-password" class="link-primary">Forgot Password?</router-link>
                                            </div>
                                        </div>

                                        <div class="mb-4">
                                            <button type="submit" class="btn btn-primary w-100" :disabled="isLoading">
                                                <span v-if="isLoading">Signing In...</span>
                                                <span v-else>Sign In</span>
                                            </button>
                                        </div>

                                        <div class="login-or position-relative mb-4 text-center">
                                            <span class="position-relative bg-white px-2 z-2">or continue with</span>
                                        </div>

                                        <div class="mt-2">
                                            <div class="d-flex align-items-center justify-content-center flex-wrap">
                                                <div class="text-center me-2 flex-fill">
                                                    <a href="#" class="btn btn-white d-flex align-items-center justify-content-center shadow">
                                                        <img class="img-fluid me-2" src="@/assets/img/icons/google.svg" alt="google">Google
                                                    </a>
                                                </div>
                                                <div class="text-center me-2 flex-fill">
                                                    <a href="#" class="btn btn-white d-flex align-items-center justify-content-center shadow">
                                                        <img class="img-fluid me-2" src="@/assets/img/icons/fb.svg" alt="facebook">Facebook
                                                    </a>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="text-center mt-4">
                                            <p class="fw-normal mb-0">Don't have an account?
                                                <router-link to="/register" class="link-primary"> Sign Up</router-link>
                                            </p>
                                        </div>
                                        
                                    </div>                                        
                                </div>

                            </form>
                        </div> <!-- end col -->

                    </div>
                    <!-- end row -->

                </div> <!-- end col -->

                <div class="col-lg-6">
                    <div class="position-relative d-lg-flex align-items-center justify-content-center d-none flex-wrap vh-100 p-4 ps-0">
                        <div class="w-100 rounded-3 position-relative h-100 bg-primary z-1 overflow-hidden">
                            <img src="@/assets/img/authentication/authentication-bg-01.png" class="img-fluid position-absolute end-0 z-n1 auth-bg-01" alt="bg">
                            <img src="@/assets/img/authentication/authentication-bg-02.png" class="img-fluid position-absolute top-0 end-0 z-n1 auth-bg-02" alt="bg">
                            <div class="px-4 rounded-3 h-100 d-flex flex-column align-items-center auth-wrap">
                                <div class="text-center z-2">
                                    <h1 class="text-white mb-2">Complete Control of Your Cafe & Restaurant with Ease</h1>
                                    <p class="text-white mb-0">From billing to inventory access everything you need in a single powerful dashboard, Analyze sales, track your best-selling dishes.</p>
                                </div>
                                <div class="text-center auth-img position-absolute bottom-0">
                                    <img src="@/assets/img/authentication/login.png" class="img-fluid position-relative z-1" alt="user">
                                </div>
                            </div>
                        </div>
                    </div>
                </div> <!-- end col -->

            </div>
            <!-- end row -->

        </div>
        <!-- End Content -->

    </div>

    <!-- ========================
        End Page Content
    ========================= -->
</template>


<script>
import { defineComponent, onMounted, onBeforeUnmount } from "vue";

export default defineComponent({
    data() {
        return {
            email: 'admin@example.com',
            password: '123456',
            rememberMe: false,
            errorMessage: '',
            isLoading: false,
            showPassword: false
        };
    },
    mounted() {
      // Check if email is passed as query parameter from registration
      if (this.$route.query.email) {
        this.email = this.$route.query.email;
      }
    },
    methods: {
        togglePassword() {
            this.showPassword = !this.showPassword;
        },
        handleLogin() {
            // Clear previous error
            this.errorMessage = '';
            this.isLoading = true;
    
            // Simulate API delay
            setTimeout(() => {
            let isAuthenticated = false;
            
            // Check default admin credentials
            if (this.email === 'admin@example.com' && this.password === '123456') {
                isAuthenticated = true;
            } else {
                // Check registered users from localStorage
                const registeredUsers = JSON.parse(localStorage.getItem('registeredUsers') || '[]');
                const user = registeredUsers.find(
                user => user.email === this.email.trim() && user.password === this.password
                );
                
                if (user) {
                isAuthenticated = true;
                }
            }
            
            
            if (isAuthenticated) {
                // Success - redirect to dashboard
                this.$router.push('/main-menu/dashboard');
            } else {
                // Show error message
                this.errorMessage = 'Invalid email or password. Please try again.';
                this.isLoading = false;
            }
            }, 1000);
        }
    },
    setup() {
        onMounted(() => {
            document.body.classList.add("bg-white");
            document.documentElement.setAttribute("data-bs-theme", "light");
        });
        onBeforeUnmount(() => {
            document.body.classList.remove("bg-white");
            document.documentElement.removeAttribute("data-bs-theme");
        });
    },
});
</script>

// frontend/src/pages-template/authentication/login/login.tsx
﻿import { useEffect, useRef, useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import Toast from "../../components-template/toast/toast";
import { useAuth } from "../auth-context/authContext";
import { all_routes } from "../../../routes/all_routes";
import ImageWithBasePath from "../../../components/ImageWithBasePath";
type PasswordField = "password" | "confirmPassword";

const Login = () => {
  const navigate = useNavigate();
  const { login } = useAuth();

  // For UI form
  const [email, setEmail] = useState("admin@gmail.com");
  const [password, setPassword] = useState("123456");

  // Toast state
  const [toast, setToast] = useState<{
    msg: string;
    type: "success" | "danger" | "warning" | "info";
  } | null>(null);

  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const showToast = (
    message: string,
    type: "success" | "danger" | "warning" | "info"
  ) => {
    if (toastTimer.current) {
      clearTimeout(toastTimer.current);
    }
    setToast({ msg: message, type });
    toastTimer.current = setTimeout(() => {
      setToast(null);
    }, 3000);
  };

  useEffect(() => {
    return () => {
      if (toastTimer.current) {
        clearTimeout(toastTimer.current);
      }
    };
  }, []);

  // Handle Login
  const handleLogin = (e: React.FormEvent) => {
    e.preventDefault();

    const trimmedEmail = email.trim();
    const trimmedPassword = password;

    if (!trimmedEmail || !trimmedPassword) {
      showToast("Veuillez remplir tous les champs !", "danger");
      return;
    }

    const result = login(trimmedEmail, trimmedPassword);

    if (!result.ok) {
      showToast(result.msg ?? "E-mail ou mot de passe invalide", "danger");
      return;
    }

    showToast("Connexion réussie !", "success");

    navigate(all_routes.dashboard, { replace: true });
  };


  const [passwordVisibility, setPasswordVisibility] = useState({
    password: false,
    confirmPassword: false,
  });

  const togglePasswordVisibility = (field: PasswordField) => {
    setPasswordVisibility((prevState) => ({
      ...prevState,
      [field]: !prevState[field],
    }));
  };

  return (
    <>
      {/* Toast Notification */}
      {toast && <Toast msg={toast.msg} type={toast.type} />}

      {/* ========================
         Start Page Content
       ========================= */}
      <div className="container-fuild">
        <div className="w-100 overflow-hidden position-relative flex-wrap d-block vh-100">
          <div className="row g-2">
            <div className="col-lg-6 col-md-12 col-sm-12 p-3">
              <div className="row justify-content-center align-items-center overflow-auto flex-wrap auth-vh vh-100">
                <div className="col-xl-8 col-lg-10 col-md-8 col-sm-10 mx-auto">
                  <form onSubmit={handleLogin}>
                    <div className="d-flex flex-column justify-content-between p-3">
                      <div className="mb-5">
                        <Link to="/">
                          <ImageWithBasePath
                            src="assets/img/logo.svg"
                            className="img-fluid"
                            alt="Logo"
                          />
                        </Link>
                      </div>

                      <div>
                        <div className="mb-4">
                          <h3 className="mb-2">Bonjour, Bon Retour !!!</h3>
                          <p className="mb-0">
                            Veuillez entrer vos identifiants pour vous connecter !
                          </p>
                        </div>

                        <div className="mb-3">
                          <label className="form-label">
                            E-mail<span className="text-danger"> *</span>
                          </label>
                          <input
                            type="email"
                            className="form-control"
                            value={email}
                            onChange={(e) => setEmail(e.target.value)}
                            placeholder="nom@exemple.com"
                          />
                        </div>

                        <div className="mb-3">
                          <label className="form-label">
                            Mot de passe<span className="text-danger"> *</span>
                          </label>

                          <div className="input-group input-group-flat pass-group">
                            <input
                              type={passwordVisibility.password ? "text" : "password"}
                              className="form-control pass-input"
                              aria-label="Password"
                              value={password}
                              onChange={(e) => setPassword(e.target.value)}
                            />
                            <span
                              className={`ti toggle-password input-group-text toggle-password ${passwordVisibility.password ? "icon-eye" : "icon-eye-off"
                                }`}
                              onClick={() => togglePasswordVisibility("password")}
                            ></span>
                          </div>
                        </div>

                        <div className="d-flex align-items-center justify-content-between mb-4">
                          <div className="form-check mb-0">
                            <input
                              className="form-check-input"
                              id="remember_me"
                              type="checkbox"
                            />
                            <label
                              htmlFor="remember_me"
                              className="form-check-label text-dark mt-0"
                            >
                              Se souvenir de moi
                            </label>
                          </div>

                          <Link to={all_routes.forgotPassword} className="link-primary">
                            Mot de passe oublié ?
                          </Link>
                        </div>

                        <div className="mb-4">
                          <button
                            type="submit"
                            className="btn btn-primary w-100"
                          >
                            Se connecter
                          </button>
                        </div>

                        <div className="login-or position-relative mb-4 text-center">
                          <span className="position-relative bg-white px-2 z-2">
                            ou continuer avec
                          </span>
                        </div>
                        <div className="d-flex align-items-center justify-content-center flex-wrap">
                          <div className="text-center me-2 flex-fill">
                            <Link
                              to="#"
                              className="btn btn-white d-flex align-items-center justify-content-center shadow"
                            >
                              <ImageWithBasePath
                                className="img-fluid me-2"
                                src="assets/img/icons/google.svg"
                                alt="google"
                              />
                              Google
                            </Link>
                          </div>
                          <div className="text-center me-2 flex-fill">
                            <Link
                              to="#"
                              className="btn btn-white d-flex align-items-center justify-content-center shadow"
                            >
                              <ImageWithBasePath
                                className="img-fluid me-2"
                                src="assets/img/icons/fb.svg"
                                alt="facebook"
                              />
                              Facebook
                            </Link>
                          </div>
                        </div>


                        <div className="text-center mt-4">
                          <p className="fw-normal mb-0">
                            Vous n'avez pas de compte ?
                            <Link to={all_routes.register} className="link-primary">
                              {" "}
                              S'inscrire
                            </Link>
                          </p>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>

            {/* Right Side Image */}
            <div className="col-lg-6">
              <div className="position-relative d-lg-flex align-items-center justify-content-center d-none flex-wrap vh-100 p-4 ps-0">
                <div className="w-100 rounded-3 position-relative h-100 bg-primary z-1 overflow-hidden">
                  <ImageWithBasePath
                    src="assets/img/authentication/authentication-bg-01.png"
                    className="img-fluid position-absolute end-0 z-n1 auth-bg-01"
                    alt="bg"
                  />
                  <ImageWithBasePath
                    src="assets/img/authentication/authentication-bg-02.png"
                    className="img-fluid position-absolute top-0 end-0 z-n1 auth-bg-02"
                    alt="bg"
                  />
                  <div className="px-4 rounded-3 h-100 d-flex flex-column align-items-center auth-wrap">
                    <div className="text-center z-2">
                      <h1 className="text-white mb-2">
                        Contrôle Complet de Votre Café &amp; Restaurant en Toute Simplicité
                      </h1>
                      <p className="text-white mb-0">
                        De la facturation à l'inventaire, accédez à tout ce dont vous avez besoin dans un tableau de bord puissant, Analysez les ventes, suivez vos plats les plus vendus.
                      </p>
                    </div>

                    <div className="text-center auth-img position-absolute bottom-0">
                      <ImageWithBasePath
                        src="assets/img/authentication/login.png"
                        className="img-fluid position-relative z-1"
                        alt="user"
                      />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* end col */}
          </div>
        </div>
      </div>
    </>
  );
};

export default Login;
