// template/react-extracted/react/template/src/pages/authentication/register/register.tsx
import { Link, useNavigate } from "react-router-dom";
import { useAuth } from "../auth-context/authContext";
import { useEffect, useRef, useState, type FormEvent } from "react";
import Toast from "../../../components/toast/toast";
import { all_routes } from "../../../routes/all_routes";
import ImageWithBasePath from "../../../components/image-with-base-path";
type PasswordField = "password" | "confirmPassword";

const Register = () => {
  const { register } = useAuth();
  const navigate = useNavigate();

  const [username, setUsername] = useState("");
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");

  const [toast, setToast] = useState<{
    msg: string;
    type: "success" | "danger" | "warning" | "info";
  } | null>(null);
  const toastTimer = useRef<ReturnType<typeof setTimeout> | null>(null);

  const showToast = (
    msg: string,
    type: "success" | "danger" | "warning" | "info"
  ) => {
    if (toastTimer.current) {
      clearTimeout(toastTimer.current);
    }
    setToast({ msg, type });
    toastTimer.current = setTimeout(() => setToast(null), 3000);
  };

  useEffect(() => {
    return () => {
      if (toastTimer.current) {
        clearTimeout(toastTimer.current);
      }
    };
  }, []);

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();

    // 🔹 Basic validations
    if (!username.trim()) {
      return showToast("Username is required!", "danger");
    }

    if (!email.includes("@")) {
      return showToast("Invalid email address!", "danger");
    }

    if (password.length < 4) {
      return showToast("Password must be at least 4 characters", "warning");
    }

    if (password !== confirmPassword) {
      return showToast("Passwords do not match!", "danger");
    }

    // 🔹 Save to localStorage (your authContext does this)
    register(email, password);

    showToast("Registered Successfully!", "success");

    // Optionally clear fields
    setUsername("");
    setEmail("");
    setPassword("");
    setConfirmPassword("");

    setTimeout(() => {
      navigate(all_routes.login, { replace: true });
    }, 400);
  };

  const [passwordVisibility, setPasswordVisibility] = useState({
    password: false,
    confirmPassword: false,
  });

  const togglePasswordVisibility = (field: PasswordField) => {
    setPasswordVisibility((prevState) => ({
      ...prevState,
      [field]: !prevState[field],
    }));
  };

  return (
    <>
      {toast && <Toast msg={toast.msg} type={toast.type} />}

      {/* ======================== Start Page Content ========================= */}
      <div className="container-fuild">
        <div className="w-100 overflow-hidden position-relative flex-wrap d-block vh-100">
          <div className="row g-2">
            <div className="col-lg-6 col-md-12 col-sm-12 p-3">
              <div className="row justify-content-center align-items-center overflow-auto flex-wrap auth-vh vh-100">
                <div className="col-xl-8 col-lg-10 col-md-8 col-sm-10 mx-auto">
                  <form onSubmit={handleSubmit}>
                    <div className="d-flex flex-column justify-content-between p-3">
                      <div className="mb-5">
                        <Link to={all_routes.dashboard}>
                          <ImageWithBasePath
                            src="assets/img/logo.svg"
                            className="img-fluid"
                            alt="Logo"
                          />
                        </Link>
                      </div>

                      <div>
                        <div className="mb-4">
                          <h3 className="mb-2">Sign Up</h3>
                          <p className="mb-0">And lets get started with your free trial</p>
                        </div>

                        {/* Username */}
                        <div className="mb-3">
                          <label className="form-label">
                            Username <span className="text-danger">*</span>
                          </label>
                          <input type="text" className="form-control" value={username} onChange={(e) => setUsername(e.target.value)} />
                        </div>

                        {/* Email */}
                        <div className="mb-3">
                          <label className="form-label">
                            Email <span className="text-danger">*</span>
                          </label>
                          <input type="email" className="form-control" value={email} onChange={(e) => setEmail(e.target.value)} />
                        </div>

                        {/* Password */}
                        <div className="mb-3">
                          <label className="form-label">
                            Password <span className="text-danger">*</span>
                          </label>
                          <div className="input-group input-group-flat pass-group">
                            <input type={ passwordVisibility.password ? "text" : "password" } className="form-control pass-input" value={password} onChange={(e) => setPassword(e.target.value)} aria-label="Password" />
                            <span className={`ti toggle-password input-group-text toggle-password ${passwordVisibility.password ? "icon-eye" : "icon-eye-off" }`}onClick={() => togglePasswordVisibility("password")}></span>
                          </div>
                        </div>

                        {/* Confirm Password */}
                        <div className="mb-3">
                          <label className="form-label">
                            Confirm Password{" "}
                            <span className="text-danger">*</span>
                          </label>
                          <div className="input-group input-group-flat pass-group">
                            <input type={ passwordVisibility.confirmPassword ? "text" : "password" } className="form-control pass-input" value={confirmPassword} onChange={(e) => setConfirmPassword(e.target.value)} aria-label="Confirm Password" />
                            <span className={`ti toggle-password input-group-text toggle-password ${passwordVisibility.confirmPassword ? "icon-eye" : "icon-eye-off" }`} onClick={() => togglePasswordVisibility("confirmPassword") } ></span>
                          </div>
                        </div>

                        {/* Remember + Forgot */}
                        <div className="d-flex align-items-center justify-content-between mb-4">
                          <div className="form-check form-check-md mb-0">
                            <input className="form-check-input" id="remember_me" type="checkbox" />
                            <label htmlFor="remember_me" className="form-check-label text-dark mt-0" >
                              Remember Me
                            </label>
                          </div>
                          <div className="text-end">
                            <Link to={all_routes.forgotPassword} className="link-primary">
                              Forgot Password?
                            </Link>
                          </div>
                        </div>

                        {/* Submit */}
                        <div className="mb-4">
                          <button
                            type="submit"
                            className="btn btn-primary w-100"
                          >
                            Sign Up
                          </button>
                        </div>

                        {/* Social Buttons */}
                        <div className="login-or position-relative mb-4 text-center">
                          <span className="position-relative bg-white px-2 z-2">
                            or continue with
                          </span>
                        </div>

                        <div className="d-flex align-items-center justify-content-center flex-wrap">
                          <div className="text-center me-2 flex-fill">
                            <Link to="#" className="btn btn-white d-flex align-items-center justify-content-center shadow" >
                              <ImageWithBasePath className="img-fluid me-2" src="assets/img/icons/google.svg" alt="google" />
                              Google
                            </Link>
                          </div>

                          <div className="text-center me-2 flex-fill">
                            <Link to="#" className="btn btn-white d-flex align-items-center justify-content-center shadow" >
                              <ImageWithBasePath className="img-fluid me-2" src="assets/img/icons/fb.svg" alt="facebook" />
                              Facebook
                            </Link>
                          </div>
                        </div>

                        {/* Login Link */}
                        <div className="text-center mt-4">
                          <p className="fw-normal mb-0">
                            Already have an account?{" "}
                            <Link to={all_routes.login} className="link-primary">
                              Sign In
                            </Link>
                          </p>
                        </div>
                      </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>

            {/* Right Side */}
            <div className="col-lg-6">
              <div className="position-relative d-lg-flex align-items-center justify-content-center d-none flex-wrap vh-100 p-4 ps-0">
                <div className="w-100 rounded-3 position-relative h-100 bg-primary z-1 overflow-hidden">
                  <ImageWithBasePath src="assets/img/authentication/authentication-bg-01.png" className="img-fluid position-absolute bottom-0 end-0 z-n1 auth-bg-01" alt="bg" />
                  <ImageWithBasePath src="assets/img/authentication/authentication-bg-02.png" className="img-fluid position-absolute top-0 end-0 z-n1 auth-bg-02" alt="bg" />
                  <div className="px-4 rounded-3 h-100 d-flex flex-column align-items-center auth-wrap">
                    <div className="text-center z-2">
                      <h1 className="text-white mb-2">
                        Complete Control of Your Cafe & Restaurant with Ease
                      </h1>
                      <p className="text-white mb-0">
                        From billing to inventory access everything you need in a single powerful dashboard, Analyze sales, track your best-selling dishes.
                      </p>
                    </div>

                    <div className="text-center auth-img position-absolute bottom-0">
                      <ImageWithBasePath src="assets/img/authentication/login.png" className="img-fluid position-relative z-1" alt="user" />
                    </div>
                  </div>
                </div>
              </div>
            </div>

            {/* End Right Side */}
          </div>
        </div>
      </div>
      {/* ======================== End Page Content ========================= */}
    </>
  );
};

export default Register;

// template/dreamspos-v2.2.4/nuxtjs-extracted/nuxtjs/template/app/components/Modules/Authentication/register/Register.vue
<template>
  <div class="main-wrapper">
    <div class="account-content">
      <div class="login-wrapper register-wrap bg-img">
        <div class="login-content authent-content">
          <form @submit.prevent="handleRegister">
            <div class="login-userset">
              <div class="login-logo logo-normal">
                <img src="@/assets/img/logo.svg" alt="img">
              </div>
              <NuxtLink to="/dashboard/admin-dashboard" class="login-logo logo-white">
                <img src="@/assets/img/logo-white.svg" alt="Img">
              </NuxtLink>
              <div class="login-userheading">
                <h3>Register</h3>
                <h4>Create New Dreamspos Account</h4>
              </div>
              <div v-if="errorMessage" class="mb-3">
                <div class="alert alert-danger" role="alert">
                  {{ errorMessage }}
                </div>
              </div>
              <div v-if="successMessage" class="mb-3">
                <div class="alert alert-success" role="alert">
                  {{ successMessage }}
                </div>
              </div>
              <div class="mb-3">
                <label class="form-label">Name <span class="text-danger"> *</span></label>
                <div class="input-group">
                  <input type="text" v-model="name" class="form-control border-end-0">
                  <span class="input-group-text border-start-0">
                    <i class="ti ti-user"></i>
                  </span>
                </div>
              </div>
              <div class="mb-3">
                <label class="form-label">Email <span class="text-danger"> *</span></label>
                <div class="input-group">
                  <input type="text" v-model="email" class="form-control border-end-0">
                  <span class="input-group-text border-start-0">
                    <i class="ti ti-mail"></i>
                  </span>
                </div>
              </div>
              <div class="mb-3">
                <label class="form-label">Password <span class="text-danger"> *</span></label>
                <div class="pass-group">
                  <input :type="showPassword ? 'text' : 'password'" v-model="password" class="pass-input form-control">
                  <span class="ti toggle-password" :class="showPassword ? 'ti-eye text-gray-9' : 'ti-eye-off text-gray-9'" @click="togglePassword"></span>
                </div>
              </div>
              <div class="mb-3">
                <label class="form-label">Confirm Password <span class="text-danger"> *</span></label>
                <div class="pass-group">
                  <input :type="showConfirmPassword ? 'text' : 'password'" v-model="confirmPassword" class="pass-inputs form-control">
                  <span class="ti toggle-passwords" :class="showConfirmPassword ? 'ti-eye text-gray-9' : 'ti-eye-off text-gray-9'" @click="toggleConfirmPassword"></span>
                </div>
              </div>
              <div class="form-login authentication-check">
                <div class="row">
                  <div class="col-sm-8">
                    <div class="custom-control custom-checkbox justify-content-start">
                      <div class="custom-control custom-checkbox">
                        <label class="checkboxs ps-4 mb-0 pb-0 line-height-1">
                          <input type="checkbox" v-model="agreeToTerms">
                          <span class="checkmarks"></span>I agree to the <a href="#" class="text-primary">Terms &
                            Privacy</a>
                        </label>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="form-login">
                <button type="submit" class="btn btn-login" :disabled="isLoading">
                  <span v-if="isLoading">Creating Account...</span>
                  <span v-else>Sign Up</span>
                </button>
              </div>
              <div class="signinform">
                <h4>Already have an account ? <NuxtLink to="/" class="hover-a">Sign In Instead</NuxtLink></h4>
              </div>
              <div class="form-setlogin or-text">
                <h4>OR</h4>
              </div>
              <div class="mt-2">
                <div class="d-flex align-items-center justify-content-center flex-wrap">
                  <div class="text-center me-2 flex-fill">
                    <a href="javascript:void(0);"
                      class="br-10 p-2 btn btn-info d-flex align-items-center justify-content-center">
                      <img class="img-fluid m-1" src="@/assets/img/icons/facebook-logo.svg" alt="Facebook">
                    </a>
                  </div>
                  <div class="text-center me-2 flex-fill">
                    <a href="javascript:void(0);"
                      class="btn btn-white br-10 p-2  border d-flex align-items-center justify-content-center">
                      <img class="img-fluid m-1" src="@/assets/img/icons/google-logo.svg" alt="Facebook">
                    </a>
                  </div>
                  <div class="text-center flex-fill">
                    <a href="javascript:void(0);"
                      class="bg-dark br-10 p-2 btn btn-dark d-flex align-items-center justify-content-center">
                      <img class="img-fluid m-1" src="@/assets/img/icons/apple-logo.svg" alt="Apple">
                    </a>
                  </div>
                </div>
              </div>
              <div class="my-4 d-flex justify-content-center align-items-center copyright-text">
                <p>Copyright &copy; 2025 DreamsPOS</p>
              </div>
            </div>
          </form>

        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  name: 'PosRegister',
  data() {
    return {
      name: '',
      email: '',
      password: '',
      confirmPassword: '',
      agreeToTerms: false,
      errorMessage: '',
      successMessage: '',
      isLoading: false,
      showPassword: false,
      showConfirmPassword: false
    };
  },
  methods: {
    togglePassword() {
      this.showPassword = !this.showPassword;
    },
    toggleConfirmPassword() {
      this.showConfirmPassword = !this.showConfirmPassword;
    },
    handleRegister() {
      // Clear previous messages
      this.errorMessage = '';
      this.successMessage = '';
      this.isLoading = true;

      // Basic validation
      if (!this.name.trim()) {
        this.errorMessage = 'Name is required.';
        this.isLoading = false;
        return;
      }

      if (!this.email.trim()) {
        this.errorMessage = 'Email is required.';
        this.isLoading = false;
        return;
      }

      // Simple email validation
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(this.email)) {
        this.errorMessage = 'Please enter a valid email address.';
        this.isLoading = false;
        return;
      }

      if (!this.password) {
        this.errorMessage = 'Password is required.';
        this.isLoading = false;
        return;
      }

      if (this.password.length < 6) {
        this.errorMessage = 'Password must be at least 6 characters long.';
        this.isLoading = false;
        return;
      }

      if (this.password !== this.confirmPassword) {
        this.errorMessage = 'Passwords do not match.';
        this.isLoading = false;
        return;
      }

      if (!this.agreeToTerms) {
        this.errorMessage = 'You must agree to the Terms & Privacy.';
        this.isLoading = false;
        return;
      }

      // Simulate API delay
      setTimeout(() => {
        // Store registered user credentials in localStorage
        const registeredUsers = JSON.parse(localStorage.getItem('registeredUsers') || '[]');
        
        // Check if email already exists
        const emailExists = registeredUsers.some(user => user.email === this.email.trim());
        if (emailExists) {
          this.errorMessage = 'This email is already registered. Please use a different email.';
          this.isLoading = false;
          return;
        }
        
        // Add new user to registered users
        registeredUsers.push({
          email: this.email.trim(),
          password: this.password,
          name: this.name.trim()
        });
        
        // Save to localStorage
        localStorage.setItem('registeredUsers', JSON.stringify(registeredUsers));
        
        // Fake registration - simulate success
        this.successMessage = 'Account created successfully! Redirecting to sign in...';
        this.isLoading = false;
        
        // Redirect to sign in page after 2 seconds with email as query parameter
        // Only pass email if it's valid
        setTimeout(() => {
          if (this.email && this.email.trim()) {
            this.$router.push({
              path: '/',
              query: { email: this.email.trim() }
            });
          } else {
            this.$router.push('/');
          }
        }, 2000);
      }, 1000);
    }
  }
};
</script>
