// template/dreamspos-v2.2.4/food-pos-vue-extracted/vue/template/src/views/pages/settings-module/print-settings.vue
<template>
    <!-- ========================
        Start Page Content
    ========================= -->
        
    <div class="page-wrapper">

        <!-- Start Content -->
        <div class="content">

            <!-- Page Header -->
            <div class="d-flex align-items-sm-center flex-sm-row flex-column gap-3 mb-4">
                <div class="flex-grow-1">
                    <h3 class="mb-0">Print Settings <a href="#" class="btn btn-icon btn-sm btn-white rounded-circle ms-2"><i class="icon-refresh-ccw"></i></a></h3>
                </div>
            </div>
            <!-- End Page Header -->

            <div>
                <!-- card start -->
                <div class="card">
                    
                    <div class="card-body">
                        <form action="#">

                            <h5 class="mb-3">Print Settings</h5>

                            <!-- start row -->
                            <div class="row">

                                <div class="col-md-12">
                                    <div class="mb-3">
                                        <div class="form-check form-switch mb-3 d-flex align-items-center justify-content-between ps-0">
                                            <label class="form-check-label" for="switchCheckChecked">Enable Print</label>
                                            <input class="form-check-input" type="checkbox" role="switch" id="switchCheckChecked" checked>
                                        </div>
                                        <div class="form-check form-switch mb-3 d-flex align-items-center justify-content-between ps-0">
                                            <label class="form-check-label" for="switchCheckChecked2">Show Store Details</label>
                                            <input class="form-check-input" type="checkbox" role="switch" id="switchCheckChecked2" checked>
                                        </div>
                                        <div class="form-check form-switch mb-3 d-flex align-items-center justify-content-between ps-0">
                                            <label class="form-check-label" for="switchCheckChecked3">Show Customer Details</label>
                                            <input class="form-check-input" type="checkbox" role="switch" id="switchCheckChecked3" checked>
                                        </div>
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-12">
                                    <div class="mb-3">
                                        <label class="form-label">Format (Page Sizes)<span class="text-danger ms-1">*</span></label>
                                        <vue-select 
                                            :options="Format"
                                            v-model="selected"
                                            placeholder="Select"
                                        />
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-12">
                                    <div class="mb-3">
                                        <label class="form-label">Header</label>
                                        <textarea class="form-control"></textarea>
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-12">
                                    <div class="mb-3">
                                        <label class="form-label">Footer</label>
                                        <textarea class="form-control"></textarea>
                                    </div>
                                </div> <!-- end col -->

                                <div class="col-md-12">
                                    <div class="mb-3">
                                        <div class="form-check form-switch d-flex align-items-center justify-content-between mb-3 ps-0">
                                            <label class="form-check-label" for="switchCheckChecked4">Show Notes</label>
                                            <input class="form-check-input" type="checkbox" role="switch" id="switchCheckChecked4" checked>
                                        </div>
                                        <div class="form-check form-switch d-flex align-items-center justify-content-between mb-3 ps-0">
                                            <label class="form-check-label" for="switchCheckChecked5">Print Tokens</label>
                                            <input class="form-check-input" type="checkbox" role="switch" id="switchCheckChecked5" checked>
                                        </div>
                                    </div>
                                </div> <!-- end col -->

                            </div>
                            <!-- end row -->

                            <div class="d-flex align-items-center justify-content-end flex-wrap row-gap-2 border-top mt-4 pt-4">
                                <button type="button" class="btn btn-light me-2">Cancel</button>
                                <button type="submit" class="btn btn-primary">Save Changes</button>
                            </div>

                        </form>
                    </div> <!-- end card body -->

                </div>
                <!-- card start -->
            </div>
                            
        </div>
        <!-- End Content -->  

    </div>

    <!-- ========================
        End Page Content
    ========================= -->
</template>

<script>
export default {
    data(){
        return {
            selected: [],
            Format: [
                { label: "Select", value: "Select" },
                { label: "A1", value: "A1" },
                { label: "A2", value: "A2" },
                { label: "A3", value: "A3" },
                { label: "A4", value: "A4" },
                { label: "A5", value: "A5" },
            ]
        }
    }
}
</script>

// template/dreamspos-v2.2.4/food-pos-react-extracted/react/template/src/pages/settings/printSettings.tsx

import { Page_Size } from "../../core/json/selectOption";
import CommonSelect from "../../components/common-select/commonSelect";
import { Link } from "react-router-dom";


const PrintSettings = () => {

    return (
        <>
            {/* ========================
			Start Page Content
		========================= */}
            <div className="page-wrapper">
                {/* Start Content */}
                <div className="content">
                    {/* Page Header */}
                    <div className="d-flex align-items-sm-center flex-sm-row flex-column gap-3 mb-4">
                        <div className="flex-grow-1">
                            <h3 className="mb-0">
                                Print Settings{" "}
                                <Link
                                    to="#"
                                    className="btn btn-icon btn-sm btn-white rounded-circle ms-2"
                                >
                                    <i className="icon-refresh-ccw" />
                                </Link>
                            </h3>
                        </div>
                    </div>
                    {/* End Page Header */}
                    <div>
                        {/* card start */}
                        <div className="card">
                            <div className="card-body">
                                <form>
                                    <h5 className="mb-3">Print Settings</h5>
                                    {/* start row */}
                                    <div className="row">
                                        <div className="col-md-12">
                                            <div className="mb-3">
                                                <div className="form-check form-switch mb-3 d-flex align-items-center justify-content-between ps-0">
                                                    <label
                                                        className="form-check-label"
                                                        htmlFor="switchCheckChecked"
                                                    >
                                                        Enable Print
                                                    </label>
                                                    <input
                                                        className="form-check-input"
                                                        type="checkbox"
                                                        role="switch"
                                                        id="switchCheckChecked"
                                                        defaultChecked
                                                    />
                                                </div>
                                                <div className="form-check form-switch mb-3 d-flex align-items-center justify-content-between ps-0">
                                                    <label
                                                        className="form-check-label"
                                                        htmlFor="switchCheckChecked2"
                                                    >
                                                        Show Store Details
                                                    </label>
                                                    <input
                                                        className="form-check-input"
                                                        type="checkbox"
                                                        role="switch"
                                                        id="switchCheckChecked2"
                                                        defaultChecked
                                                    />
                                                </div>
                                                <div className="form-check form-switch mb-3 d-flex align-items-center justify-content-between ps-0">
                                                    <label
                                                        className="form-check-label"
                                                        htmlFor="switchCheckChecked3"
                                                    >
                                                        Show Customer Details
                                                    </label>
                                                    <input
                                                        className="form-check-input"
                                                        type="checkbox"
                                                        role="switch"
                                                        id="switchCheckChecked3"
                                                        defaultChecked
                                                    />
                                                </div>
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-12">
                                            <div className="mb-3">
                                                <label className="form-label">
                                                    Format (Page Sizes)
                                                    <span className="text-danger ms-1">*</span>
                                                </label>
                                                <CommonSelect
                                                    options={Page_Size}
                                                    className="select"
                                                    defaultValue={Page_Size[0]}
                                                />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-12">
                                            <div className="mb-3">
                                                <label className="form-label">Header</label>
                                                <textarea className="form-control" defaultValue={""} />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-12">
                                            <div className="mb-3">
                                                <label className="form-label">Footer</label>
                                                <textarea className="form-control" defaultValue={""} />
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                        <div className="col-md-12">
                                            <div className="mb-3">
                                                <div className="form-check form-switch d-flex align-items-center justify-content-between mb-3 ps-0">
                                                    <label
                                                        className="form-check-label"
                                                        htmlFor="switchCheckChecked4"
                                                    >
                                                        Show Notes
                                                    </label>
                                                    <input
                                                        className="form-check-input"
                                                        type="checkbox"
                                                        role="switch"
                                                        id="switchCheckChecked4"
                                                        defaultChecked
                                                    />
                                                </div>
                                                <div className="form-check form-switch d-flex align-items-center justify-content-between mb-3 ps-0">
                                                    <label
                                                        className="form-check-label"
                                                        htmlFor="switchCheckChecked5"
                                                    >
                                                        Print Tokens
                                                    </label>
                                                    <input
                                                        className="form-check-input"
                                                        type="checkbox"
                                                        role="switch"
                                                        id="switchCheckChecked5"
                                                        defaultChecked
                                                    />
                                                </div>
                                            </div>
                                        </div>{" "}
                                        {/* end col */}
                                    </div>
                                    {/* end row */}
                                    <div className="d-flex align-items-center justify-content-end flex-wrap row-gap-2 border-top mt-2 pt-4">
                            <button type="button" className="btn btn-light me-2">
                                Cancel
                            </button>
                            <button type="submit" className="btn btn-primary">
                                Save Changes
                            </button>
                        </div>
                                </form>
                            </div>{" "}
                            {/* end card body */}
                        </div>
                        {/* card start */}
                        
                    </div>
                </div>
                {/* End Content */}
            </div>
            {/* ========================
			End Page Content
		========================= */}
        </>

    )
}

export default PrintSettings
