// template/dreamspos-v2.2.4/nextjs-extracted/nextjs/template/src/components/application/contacts.tsx
"use client";
/* eslint-disable @next/next/no-img-element */

import CollapesIcon from "@/core/common/tooltip-content/collapes";
import RefreshIcon from "@/core/common/tooltip-content/refresh";
import TooltipIcons from "@/core/common/tooltip-content/tooltipIcons";
import { contact_data } from "@/core/json/contactsData";
import Link from "next/link";
import  Table  from "@/core/common/pagination/datatable";
import { PlusCircle } from "react-feather";
import Select from "react-select";
import { contactType } from "@/core/common/selectOption/selectOption";

export default function ContactsComponent(){
    const data = contact_data;

    const columns = [
        {
            title: "Name",
            dataIndex: "Name",
            render: (text:any, record:any) => (
                <div className="d-flex align-items-center">
                    <Link href="#" className="avatar avatar-md me-2">
                        <img src={record.image} alt="product" />
                    </Link>
                    <Link href="#">{text}</Link>
                </div>

            ),
            sorter: (a:any, b:any) => a.Name.length - b.Name.length,
        },
        {
            title: "Email",
            dataIndex: "Email",
            sorter: (a:any, b:any) => a.Email.length - b.Email.length,
        },

        {
            title: "Phone",
            dataIndex: "Phone",
            sorter: (a:any, b:any) => a.Phone.length - b.Phone.length,
        },
        {
            title: "Role",
            dataIndex: "Role",
            sorter: (a:any, b:any) => a.Role.length - b.Role.length,
        },
        {
            title: "Status",
            dataIndex: "Status",
            render: (text:any) => (
                <>
                    <span className="d-inline-flex align-items-center p-1 pe-2 rounded-1 text-white bg-success fs-10">
                        <i className="ti ti-point-filled me-1 fs-11" />
                        {text}
                    </span>

                </>
            ),
            sorter: (a:any, b:any) => a.Status.length - b.Status.length,
        },

        {
            title: "Action",
            dataIndex: "action",
            render: () => (
                <div className="edit-delete-action d-flex align-items-center">
                    <Link
                        className="me-2 p-2 d-flex align-items-center border rounded"
                        href="#"
                        data-bs-toggle="modal"
                        data-bs-target="#edit-contact"
                    >
                        <i data-feather="edit" className="feather-edit" />
                    </Link>
                    <Link
                        data-bs-toggle="modal"
                        data-bs-target="#delete-modal"
                        className="p-2 d-flex align-items-center border rounded"
                        href="#"
                    >
                        <i data-feather="trash-2" className="feather-trash-2" />
                    </Link>
                </div>

            ),
            sorter: (a:any, b:any) => a.createdby.length - b.createdby.length,
        },
    ];
    return(
        <div>
        <div className="page-wrapper">
            <div className="content">
                <div className="page-header">
                    <div className="add-item d-flex">
                        <div className="page-title">
                            <h4 className="fw-bold">Contacts</h4>
                            <h6>Manage your contacts</h6>
                        </div>
                    </div>
                    <ul className="table-top-head">
                        <TooltipIcons />
                        <RefreshIcon />
                        <CollapesIcon />
                    </ul>
                    <div className="page-btn">
                        <Link
                            href="#"
                            className="btn btn-primary text-white"
                            data-bs-toggle="modal"
                            data-bs-target="#add-contact"
                        >
                            <i className="ti ti-circle-plus me-1" />
                            Add Contact
                        </Link>
                    </div>
                </div>
                {/* /product list */}
                <div className="card">
                    <div className="card-header d-flex align-items-center justify-content-between flex-wrap row-gap-3">
                        <div className="search-set">
                        </div>
                        <div className="d-flex table-dropdown my-xl-auto right-content align-items-center flex-wrap row-gap-3">
                            <div className="dropdown me-2">
                                <Link
                                    href="#"
                                    className="dropdown-toggle btn btn-white btn-md d-inline-flex align-items-center"
                                    data-bs-toggle="dropdown"
                                >
                                    Status
                                </Link>
                                <ul className="dropdown-menu  dropdown-menu-end p-3">
                                    <li>
                                        <Link
                                            href="#"
                                            className="dropdown-item rounded-1"
                                        >
                                            Active
                                        </Link>
                                    </li>
                                    <li>
                                        <Link
                                            href="#"
                                            className="dropdown-item rounded-1"
                                        >
                                            Inactive
                                        </Link>
                                    </li>
                                </ul>
                            </div>
                            <div className="dropdown">
                                <Link
                                    href="#"
                                    className="dropdown-toggle btn btn-white btn-md d-inline-flex align-items-center"
                                    data-bs-toggle="dropdown"
                                >
                                    Sort By : Last 7 Days
                                </Link>
                                <ul className="dropdown-menu  dropdown-menu-end p-3">
                                    <li>
                                        <Link
                                            href="#"
                                            className="dropdown-item rounded-1"
                                        >
                                            Recently Added
                                        </Link>
                                    </li>
                                    <li>
                                        <Link
                                            href="#"
                                            className="dropdown-item rounded-1"
                                        >
                                            Ascending
                                        </Link>
                                    </li>
                                    <li>
                                        <Link
                                            href="#"
                                            className="dropdown-item rounded-1"
                                        >
                                            Desending
                                        </Link>
                                    </li>
                                    <li>
                                        <Link
                                            href="#"
                                            className="dropdown-item rounded-1"
                                        >
                                            Last Month
                                        </Link>
                                    </li>
                                    <li>
                                        <Link
                                            href="#"
                                            className="dropdown-item rounded-1"
                                        >
                                            Last 7 Days
                                        </Link>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div className="card-body p-0">
                        <div className="table-responsive">
                            <Table columns={columns} dataSource={data} />
                        </div>
                    </div>
                </div>
                {/* /product list */}
            </div>
            <div className="footer d-sm-flex align-items-center justify-content-between border-top bg-white p-3">
                <p className="mb-0 text-gray-9">
                    2014 - 2025 © DreamsPOS. All Right Reserved
                </p>
                <p>
                    Designed &amp; Developed by{" "}
                    <Link href="#" className="text-primary">
                        Dreams
                    </Link>
                </p>
            </div>
        </div>
        <>
            {/* Add Customer */}
            <div className="modal fade" id="add-contact">
                <div className="modal-dialog modal-dialog-centered">
                    <div className="modal-content">
                        <div className="modal-header">
                            <div className="page-title">
                                <h4>Add Contact</h4>
                            </div>
                            <button
                                type="button"
                                className="close"
                                data-bs-dismiss="modal"
                                aria-label="Close"
                            >
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <form >
                            <div className="modal-body">
                                <div className="new-employee-field">
                                    <div className="profile-pic-upload">
                                        <div className="profile-pic">
                                            <span>
                                                <PlusCircle size={14} className="plus-down-add" />
                                                Add Image
                                            </span>
                                        </div>
                                        <div className="mb-3">
                                            <div className="image-upload mb-0">
                                                <input type="file" />
                                                <div className="image-uploads">
                                                    <h4>Upload Image</h4>
                                                </div>
                                            </div>
                                            <p className="mt-2">JPEG, PNG up to 2 MB</p>
                                        </div>
                                    </div>
                                </div>
                                <div className="row">
                                    <div className="col-lg-6 mb-3">
                                        <label className="form-label">
                                            First Name<span className="text-danger ms-1">*</span>
                                        </label>
                                        <input type="text" className="form-control" />
                                    </div>
                                    <div className="col-lg-6 mb-3">
                                        <label className="form-label">
                                            Last Name<span className="text-danger ms-1">*</span>
                                        </label>
                                        <input type="text" className="form-control" />
                                    </div>
                                    <div className="col-lg-12 mb-3">
                                        <label className="form-label">
                                            Email<span className="text-danger ms-1">*</span>
                                        </label>
                                        <input type="email" className="form-control" />
                                    </div>
                                    <div className="col-lg-12 mb-3">
                                        <label className="form-label">
                                            Phone<span className="text-danger ms-1">*</span>
                                        </label>
                                        <input type="tel" className="form-control" />
                                    </div>
                                    <div className="col-lg-12">
                                        <div className="mb-3">
                                            <label className="form-label">
                                                Contact Type <span className="text-danger">*</span>
                                            </label>
                                            <Select
                                                classNamePrefix="react-select"
                                                options={contactType}
                                                placeholder="Choose"
                                            />
                                        </div>
                                    </div>
                                    <div className="col-lg-12">
                                        <div className="status-toggle modal-status d-flex justify-content-between align-items-center">
                                            <span className="status-label">Status</span>
                                            <input
                                                type="checkbox"
                                                id="user2"
                                                className="check"
                                                defaultChecked
                                            />
                                            <label htmlFor="user2" className="checktoggle">
                                                {" "}
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="modal-footer">
                                <button
                                    type="button"
                                    className="btn me-2 btn-secondary fs-13 fw-medium p-2 px-3 shadow-none"
                                    data-bs-dismiss="modal"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="submit"
                                    className="btn btn-primary fs-13 fw-medium p-2 px-3"
                                >
                                    Add Contact
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {/* /Add Customer */}
            {/* Edit Customer */}
            <div className="modal fade" id="edit-contact">
                <div className="modal-dialog modal-dialog-centered">
                    <div className="modal-content">
                        <div className="modal-header">
                            <div className="page-title">
                                <h4>Edit Contact</h4>
                            </div>
                            <button
                                type="button"
                                className="close"
                                data-bs-dismiss="modal"
                                aria-label="Close"
                            >
                                <span aria-hidden="true">×</span>
                            </button>
                        </div>
                        <form >
                            <div className="modal-body">
                                <div className="new-employee-field">
                                    <div className="profile-pic-upload image-field">
                                        <div className="profile-pic p-2">
                                            <img
                                                src="./assets/img/users/user-41.jpg"
                                                className="object-fit-cover h-100 rounded-1"
                                                alt="user"
                                            />
                                            <button type="button" className="close rounded-1">
                                                <span aria-hidden="true">×</span>
                                            </button>
                                        </div>
                                        <div className="mb-3">
                                            <div className="image-upload mb-0">
                                                <input type="file" />
                                                <div className="image-uploads">
                                                    <h4>Change Image</h4>
                                                </div>
                                            </div>
                                            <p className="mt-2">JPEG, PNG up to 2 MB</p>
                                        </div>
                                    </div>
                                </div>
                                <div className="row">
                                    <div className="col-lg-6 mb-3">
                                        <label className="form-label">
                                            First Name<span className="text-danger ms-1">*</span>
                                        </label>
                                        <input
                                            type="text"
                                            className="form-control"
                                            defaultValue="Carl"
                                        />
                                    </div>
                                    <div className="col-lg-6 mb-3">
                                        <label className="form-label">
                                            Last Name<span className="text-danger ms-1">*</span>
                                        </label>
                                        <input
                                            type="text"
                                            className="form-control"
                                            defaultValue="Evans"
                                        />
                                    </div>
                                    <div className="col-lg-12 mb-3">
                                        <label className="form-label">
                                            Email<span className="text-danger ms-1">*</span>
                                        </label>
                                        <input
                                            type="email"
                                            className="form-control"
                                            defaultValue="carlevans@example.com"
                                        />
                                    </div>
                                    <div className="col-lg-12 mb-3">
                                        <label className="form-label">
                                            Phone<span className="text-danger ms-1">*</span>
                                        </label>
                                        <input
                                            type="tel"
                                            className="form-control"
                                            defaultValue={+12163547758}
                                        />
                                    </div>
                                    <div className="col-lg-12">
                                        <div className="mb-3">
                                            <label className="form-label">
                                                Contact Type <span className="text-danger">*</span>
                                            </label>
                                            <Select
                                                classNamePrefix="react-select"
                                                options={contactType}
                                                placeholder="Choose"
                                            />
                                        </div>
                                    </div>
                                    <div className="col-lg-12">
                                        <div className="status-toggle modal-status d-flex justify-content-between align-items-center">
                                            <span className="status-label">Status</span>
                                            <input
                                                type="checkbox"
                                                id="user1"
                                                className="check"
                                                defaultChecked
                                            />
                                            <label htmlFor="user1" className="checktoggle">
                                                {" "}
                                            </label>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="modal-footer">
                                <button
                                    type="button"
                                    className="btn me-2 btn-secondary fs-13 fw-medium p-2 px-3 shadow-none"
                                    data-bs-dismiss="modal"
                                >
                                    Cancel
                                </button>
                                <button
                                    type="button"
                                    className="btn btn-primary fs-13 fw-medium p-2 px-3" data-bs-dismiss="modal"
                                >
                                    Save Changes
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {/* /Edit Customer */}
            {/* delete modal */}
            <div className="modal fade" id="delete-modal">
                <div className="modal-dialog modal-dialog-centered">
                    <div className="modal-content">
                        <div className="page-wrapper-new p-0">
                            <div className="content p-5 px-3 text-center">
                                <span className="rounded-circle d-inline-flex p-2 bg-danger-transparent mb-2">
                                    <i className="ti ti-trash fs-24 text-danger" />
                                </span>
                                <h4 className="fs-20 fw-bold mb-2 mt-1">Delete Contact</h4>
                                <p className="mb-0 fs-16">
                                    Are you sure you want to delete contact?
                                </p>
                                <div className="modal-footer-btn mt-3 d-flex justify-content-center">
                                    <button
                                        type="button"
                                        className="btn me-2 btn-secondary fs-13 fw-medium p-2 px-3 shadow-none"
                                        data-bs-dismiss="modal"
                                    >
                                        Cancel
                                    </button>
                                    <button
                                        type="button"
                                        className="btn btn-primary fs-13 fw-medium p-2 px-3" data-bs-dismiss="modal"
                                    >
                                        Yes Delete
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>

    </div>
    )
}

// template/dreamspos-v2.2.4/nuxtjs-extracted/nuxtjs/template/app/components/Application/Contacts.vue
<template>
    <div class="page-wrapper">
        <div class="content">
            <div class="page-header">
                <div class="add-item d-flex">
                    <div class="page-title">
                        <h4 class="fw-bold">Contacts</h4>
                        <h6>Manage your contacts</h6>
                    </div>
                </div>
                <ul class="table-top-head">
                    <li>
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Pdf"><img src="@/assets/img/icons/pdf.svg" alt="img"></a>
                    </li>
                    <li>
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Excel"><img src="@/assets/img/icons/excel.svg" alt="img"></a>
                    </li>
                    <li>
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Refresh"><i class="ti ti-refresh"></i></a>
                    </li>
                    <li>
                        <a data-bs-toggle="tooltip" data-bs-placement="top" title="Collapse" id="collapse-header" @click="toggleHeader"><i class="ti ti-chevron-up"></i></a>
                    </li>
                </ul>
                <div class="page-btn">
                    <a href="#" class="btn btn-primary text-white" data-bs-toggle="modal" data-bs-target="#add-units"><i class="ti ti-circle-plus me-1"></i>Add Contact</a>
                </div>
            </div>
            <!-- /product list -->
            <div class="card table-list-card">
                <div class="card-header d-flex align-items-center justify-content-between flex-wrap row-gap-3">
                    <div class="search-set">
                        <div class="search-input">
                            <a href="#" class="btn-searchset"><i data-feather="search" class="feather-search"></i></a>
                            <input type="search" class="form-control form-control-sm" placeholder="Search">
                        </div>
                    </div>
                    <div class="d-flex table-dropdown my-xl-auto right-content align-items-center flex-wrap row-gap-3">
                                
                        <div class="dropdown me-2">
                            <a href="#" class="dropdown-toggle btn btn-white btn-md d-inline-flex align-items-center" data-bs-toggle="dropdown">
                                Status
                            </a>
                            <ul class="dropdown-menu  dropdown-menu-end p-3">
                                <li>
                                    <a href="#" class="dropdown-item rounded-1">Active</a>
                                </li>
                                <li>
                                    <a href="#" class="dropdown-item rounded-1">Inactive</a>
                                </li>
                    
                            </ul>
                        </div>
                        <div class="dropdown">
                            <a href="#" class="dropdown-toggle btn btn-white btn-md d-inline-flex align-items-center" data-bs-toggle="dropdown">
                                Sort By : Last 7 Days
                            </a>
                            <ul class="dropdown-menu  dropdown-menu-end p-3">
                                <li>
                                    <a href="#" class="dropdown-item rounded-1">Recently Added</a>
                                </li>
                                <li>
                                    <a href="#" class="dropdown-item rounded-1">Ascending</a>
                                </li>
                                <li>
                                    <a href="#" class="dropdown-item rounded-1">Desending</a>
                                </li>
                                <li>
                                    <a href="#" class="dropdown-item rounded-1">Last Month</a>
                                </li>
                                <li>
                                    <a href="#" class="dropdown-item rounded-1">Last 7 Days</a>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="card-body">	
                    <div class="table-responsive">
                        <a-table :columns="columns" :data-source="data" :row-selection="{}">
                            <template #bodyCell="{ column, record }">
                                <template v-if="column.key === 'Name'">
                                    <div class="d-flex align-items-center">
                                        <a href="#" class="avatar avatar-md me-2">
                                            <img :src="getImageUrl(record.Image)" alt="product">
                                        </a>
                                        <a href="#">{{record.Name}}</a>
                                    </div>
                                </template>
                                <template v-else-if="column.key === 'Status'">
                                    <span class="d-inline-flex align-items-center p-1 pe-2 rounded-1 text-white bg-success fs-10">
                                        <i class="ti ti-point-filled me-1 fs-11"></i>{{record.Status}}
                                    </span>
                                </template>
                                <template v-else-if="column.key === 'action'">
                                    <div class="d-flex">
                                        <div class="edit-delete-action d-flex align-items-center">
                                            <a class="me-2 p-2 d-flex align-items-center border rounded" href="#" data-bs-toggle="modal" data-bs-target="#edit-units">
                                                <i data-feather="edit" class="feather-edit"></i>
                                            </a>
                                            <a data-bs-toggle="modal" data-bs-target="#delete-modal" class="p-2 d-flex align-items-center border rounded" href="#">
                                                <i data-feather="trash-2" class="feather-trash-2"></i>
                                            </a>
                                        </div>         
                                    </div>                               
                                </template>
                            </template>
                        </a-table>
                    </div>
                </div>
            </div>
            <!-- /product list -->
        </div>
        <div class="footer d-sm-flex align-items-center justify-content-between border-top bg-white p-3">
            <p class="mb-0 text-gray-9">2014-2025 © DreamsPOS. All Right Reserved</p>
            <p>Designed &amp; Developed By <a href="#" class="text-primary">Dreams</a></p>
        </div>
    </div>

    <ModalContactsModal />
</template>

<script>
const data = [
 {
   "Id": "1",
   "Image": "user-33.png",
   "Name": "Carl Evans",
   "Email": "carlevans@example.com",
   "Phone": "12163547758",
   "Role": "Admin",
   "Status": "Active"
 },
 {
   "Id": "2",
   "Image": "user-02.jpg",
   "Name": "Minerva Rameriz",
   "Email": "rameriz@example.com",
   "Phone": "11367529510",
   "Role": "Manager",
   "Status": "Active"
 },
 {
   "Id": "3",
   "Image": "user-34.jpg",
   "Name": "Robert Lamon",
   "Email": "robert@example.com",
   "Phone": "15362789414",
   "Role": "Salesman",
   "Status": "Active"
 },
 {
   "Id": "4",
   "Image": "user-35.jpg",
   "Name": "Patricia Lewis",
   "Email": "patricia@example.com",
   "Phone": "18513094627",
   "Role": "Supervisor",
   "Status": "Active"
 },
 {
   "Id": "5",
   "Image": "user-36.jpg",
   "Name": "Mark Joslyn",
   "Email": "markjoslyn@example.com",
   "Phone": "14678219025",
   "Role": "Store Keeper",
   "Status": "Active"
 },
 {
   "Id": "6",
   "Image": "user-37.jpg",
   "Name": "Marsha Betts",
   "Email": "marshabetts@example.com",
   "Phone": "10913278319",
   "Role": "Purchase",
   "Status": "Active"
 },
 {
   "Id": "7",
   "Image": "user-28.jpg",
   "Name": "Daniel Jude",
   "Email": "daieljude@example.com",
   "Phone": "19125852947",
   "Role": "Delivery Biker",
   "Status": "Active"
 },
 {
   "Id": "8",
   "Image": "user-38.jpg",
   "Name": "Emma Bates",
   "Email": "emmabates@example.com",
   "Phone": "13671835209",
   "Role": "Maintenance",
   "Status": "Active"
 },
 {
   "Id": "9",
   "Image": "user-39.jpg",
   "Name": "Richard Fralick",
   "Email": "richard@example.com",
   "Phone": "19756194733",
   "Role": "Quality Analyst",
   "Status": "Active"
 },
 {
   "Id": "10",
   "Image": "user-40.jpg",
   "Name": "Michelle Robison",
   "Email": "robinson@example.com",
   "Phone": "19167850925",
   "Role": "Accountant",
   "Status": "Active"
 }
]

const columns = [
    {
        sorter: true,
    },
    {
        title: "Name",
        dataIndex: "Name",
        key: "Name",
        sorter: {
            compare: (a, b) => {
                a = a.Name.toLowerCase();
                b = b.Name.toLowerCase();
                return a > b ? -1 : b > a ? 1 : 0;
            },
        },
    },
    {
        title: "Email",
        dataIndex: "Email",
        sorter: {
            compare: (a, b) => {
                a = a.Email.toLowerCase();
                b = b.Email.toLowerCase();
                return a > b ? -1 : b > a ? 1 : 0;
            },
        },
    },
    {
        title: "Phone",
        dataIndex: "Phone",
        sorter: {
            compare: (a, b) => {
                a = a.Phone.toLowerCase();
                b = b.Phone.toLowerCase();
                return a > b ? -1 : b > a ? 1 : 0;
            },
        },
    },
    {
        title: "Role",
        dataIndex: "Role",
        sorter: {
            compare: (a, b) => {
                a = a.Role.toLowerCase();
                b = b.Role.toLowerCase();
                return a > b ? -1 : b > a ? 1 : 0;
            },
        },
    },
    {
        title: "Status",
        dataIndex: "Status",
        key: "Status",
        sorter: {
            compare: (a, b) => {
                a = a.Status.toLowerCase();
                b = b.Status.toLowerCase();
                return a > b ? -1 : b > a ? 1 : 0;
            },
        },
    },
    {
        title: "Action",
        key: "action",
        sorter: true,
    },
]

export default {
    data() {
        return {
            columns,
            data,
        }
    },
    methods: {
        toggleHeader() {
            document.getElementById("collapse-header").classList.toggle("active");
            document.body.classList.toggle("header-collapse");
        },
        getImageUrl(imageName) {
            return new URL(`/assets/img/users/${imageName}`, import.meta.url).href;
        },
    },
}
</script>
