// template/dreamspos-v2.2.4/vue-extracted/vue/template/src/views/pages/hrm/edit-employee.vue
<template>
  <layout-header></layout-header>
  <layout-sidebar></layout-sidebar>
  <div class="page-wrapper">
    <div class="content">
      <div class="page-header">
        <div class="add-item d-flex">
          <div class="page-title">
            <h4>Edit Employee</h4>
            <h6>Edit Employee</h6>
          </div>
        </div>
        <ul class="table-top-head">
          <li class="me-2">
            <a data-bs-toggle="tooltip" data-bs-placement="top" title="Refresh"
              ><i class="ti ti-refresh"></i
            ></a>
          </li>
          <li>
            <a
              data-bs-toggle="tooltip"
              data-bs-placement="top"
              title="Collapse"
              id="collapse-header" @click="toggleHeader"
              ><i data-feather="chevron-up" class="feather-chevron-up"></i
            ></a>
          </li>
          <li>
            <div class="page-btn">
              <router-link to="/hrm/employees-list" class="btn btn-secondary w-100"
                ><vue-feather type="arrow-left" class="me-2"></vue-feather>Back to
                List</router-link
              >
            </div>
          </li>
        </ul>
      </div>

      <!-- /product list -->
      <form action="#">
        <div class="accordion-card-one accordion" id="accordionExample">
          <div class="accordion-item">
            <div class="accordion-header p-3" id="headingOne">
              <div
                class="accordion-button"
                data-bs-toggle="collapse"
                data-bs-target="#collapseOne"
                aria-controls="collapseOne"
              >
                <div
                  class="addproduct-icon d-flex align-items-center justify-content-between flex-fill"
                >
                  <h5 class="d-inline-flex align-items-center">
                    <i data-feather="info" class="feather-info text-primary me-2"></i
                    ><span>Employee Information</span>
                  </h5>
                  <a href="javascript:void(0);"
                    ><i data-feather="chevron-down" class="chevron-down-add"></i
                  ></a>
                </div>
              </div>
            </div>
            <div
              id="collapseOne"
              class="accordion-collapse collapse show"
              aria-labelledby="headingOne"
              data-bs-parent="#accordionExample"
            >
              <div class="accordion-body">
                <div class="new-employee-field">
                  <div class="profile-pic-upload edit-pic">
                    <div class="profile-pic">
                      <span><img src="@/assets/img/users/user-01.jpg" alt="Img" /></span>
                    </div>
                    <div class="me-3 mb-0">
                      <div class="image-upload mb-0">
                        <input type="file" />
                        <div class="image-uploads">
                          <h4>Change Image</h4>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label"
                          >First Name<span class="text-danger ms-1">*</span></label
                        >
                        <input type="text" class="form-control" value="Mitchum" />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label"
                          >Last Name<span class="text-danger ms-1">*</span></label
                        >
                        <input type="text" class="form-control" value="Daniel" />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label"
                          >Email<span class="text-danger ms-1">*</span></label
                        >
                        <input
                          type="email"
                          class="form-control"
                          value="mir34345@example.com"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label"
                          >Contact Number<span class="text-danger ms-1">*</span></label
                        >
                        <input type="text" class="form-control" value="+1 54554 54788" />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label"
                          >Emp Code<span class="text-danger ms-1">*</span></label
                        >
                        <input type="text" class="form-control" value="POS001" />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="input-blocks">
                        <label class="form-label"
                          >Date of Birth<span class="text-danger ms-1">*</span></label
                        >
                        <div class="input-groupicon calender-input">
                          <a-date-picker v-model:value="value1" class="datetimepicker form-control" />
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label"
                          >Gender<span class="text-danger ms-1">*</span></label
                        >
                        <vue-select
                          :options="Empmale"
                          v-model="selected"
                          placeholder="Male"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label"
                          >Nationality<span class="text-danger ms-1">*</span></label
                        >
                        <vue-select
                          :options="EmpNat"
                          v-model="selectedOne"
                          placeholder="United Kingdom"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="input-blocks">
                        <label class="form-label"
                          >Joining Date<span class="text-danger ms-1">*</span></label
                        >
                        <div class="input-groupicon calender-input">
                          <a-date-picker v-model:value="value2" class="datetimepicker form-control" />
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <div class="add-newplus">
                          <label class="form-label"
                            >Shift<span class="text-danger ms-1">*</span></label
                          >
                          <a href="#"
                            ><span
                              ><vue-feather
                                type="plus-circle"
                                class="plus-down-add"
                              ></vue-feather
                              >Add new</span
                            ></a
                          >
                        </div>
                        <vue-select
                          :options="ChoEmp"
                          v-model="selectedTwo"
                          placeholder="Regular"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label"
                          >Department<span class="text-danger ms-1">*</span></label
                        >
                        <vue-select
                          :options="DepEmp"
                          v-model="selectedThree"
                          placeholder="UI/UX"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label"
                          >Designation<span class="text-danger ms-1">*</span></label
                        >
                        <vue-select
                          :options="DesEmp"
                          v-model="selectedFour"
                          placeholder="Designer"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label"
                          >Blood Group<span class="text-danger ms-1">*</span></label
                        >
                        <vue-select
                          :options="BloodEmp"
                          v-model="selectedFive"
                          placeholder="O Postive"
                        />
                      </div>
                    </div>
                    <!-- Editor -->
                    <div class="col-lg-12">
                      <div class="input-blocks summer-description-box transfer mb-3">
                        <label>About</label>
                        <div id="summernote">
                          <div class="editor pages-editor">
                            <div class="editor three-line">
                              <div class="editor-container">
                                <div ref="editorRef" class="quill-editor" />
                              </div>
                            </div>
                          </div>
                        </div>
                        <p class="mt-1">Maximum 60 Characters</p>
                      </div>
                    </div>
                    <!-- /Editor -->
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <div class="accordion-header p-3" id="heading3">
              <div
                class="accordion-button"
                data-bs-toggle="collapse"
                data-bs-target="#collapseThree"
                aria-controls="collapseThree"
              >
                <div
                  class="addproduct-icon d-flex align-items-center justify-content-between flex-fill"
                >
                  <h5 class="d-inline-flex align-items-center">
                    <i data-feather="map-pin" class="feather-edit text-primary me-2"></i
                    ><span>Address Information</span>
                  </h5>
                  <a href="javascript:void(0);"
                    ><i data-feather="chevron-down" class="chevron-down-add"></i
                  ></a>
                </div>
              </div>
            </div>
            <div
              id="collapseThree"
              class="accordion-collapse collapse show"
              aria-labelledby="heading3"
              data-bs-parent="#accordionExample"
            >
              <div class="accordion-body">
                <div class="other-info">
                  <div class="row">
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">Address</label>
                        <input
                          type="text"
                          class="form-control"
                          value="1861 Bayonne Ave, Manchester"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">Country</label>
                        <vue-select
                          :options="ChooseEmpCou"
                          v-model="selectedSix"
                          placeholder="United Kingdom"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">State</label>
                        <vue-select
                          :options="ChooseEmpStaOne"
                          v-model="selectedSeven"
                          placeholder="California"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">City</label>
                        <vue-select
                          :options="ChooseEmpCityOne"
                          v-model="selectedEight"
                          placeholder="Los Angeles"
                        />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">Zipcode</label>
                        <input type="text" class="form-control" value="90001" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <div class="accordion-header p-3" id="heading4">
              <div
                class="accordion-button"
                data-bs-toggle="collapse"
                data-bs-target="#collapseFour"
                aria-controls="collapseFour"
              >
                <div
                  class="addproduct-icon d-flex align-items-center justify-content-between flex-fill"
                >
                  <h5 class="d-inline-flex align-items-center">
                    <i data-feather="info" class="feather-edit text-primary me-2"></i
                    ><span>Emergency Information</span>
                  </h5>
                  <a href="javascript:void(0);"
                    ><i data-feather="chevron-down" class="chevron-down-add"></i
                  ></a>
                </div>
              </div>
            </div>
            <div
              id="collapseFour"
              class="accordion-collapse collapse show"
              aria-labelledby="heading4"
              data-bs-parent="#accordionExample"
            >
              <div class="accordion-body">
                <div class="other-info">
                  <div class="row">
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">Emergency Contact Number 1</label>
                        <input type="text" class="form-control" value="+1 43566 67788" />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">Relation</label>
                        <input type="text" class="form-control" value="Mother" />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">Name</label>
                        <input type="text" class="form-control" value="Andrea Jermiah" />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">Emergency Contact Number 2</label>
                        <input type="text" class="form-control" />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">Relation</label>
                        <input type="text" class="form-control" />
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">Name</label>
                        <input type="text" class="form-control" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <div class="accordion-header p-3" id="heading5">
              <div
                class="accordion-button"
                data-bs-toggle="collapse"
                data-bs-target="#collapseFive"
                aria-controls="collapseFive"
              >
                <div
                  class="addproduct-icon d-flex align-items-center justify-content-between flex-fill"
                >
                  <h5 class="d-inline-flex align-items-center">
                    <i class="ti ti-building-bank feather-edit text-primary me-2"></i
                    ><span>Bank Information</span>
                  </h5>
                  <a href="javascript:void(0);"
                    ><i data-feather="chevron-down" class="chevron-down-add"></i
                  ></a>
                </div>
              </div>
            </div>
            <div
              id="collapseFive"
              class="accordion-collapse collapse show"
              aria-labelledby="heading5"
              data-bs-parent="#accordionExample"
            >
              <div class="accordion-body">
                <div class="other-info">
                  <div class="row">
                    <div class="col-lg-3 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">Bank Name</label>
                        <input
                          type="text"
                          class="form-control"
                          value="Swizz International"
                        />
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">Account Number</label>
                        <input type="text" class="form-control" value="350501501690" />
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">IFSC</label>
                        <input type="text" class="form-control" value="SW7994" />
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-6">
                      <div class="mb-3">
                        <label class="form-label">Branch</label>
                        <input type="text" class="form-control" value="Alabama USA" />
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="accordion-item">
            <div class="accordion-header p-3" id="heading6">
              <div
                class="accordion-button"
                data-bs-toggle="collapse"
                data-bs-target="#collapseTwo"
                aria-controls="collapseTwo"
              >
                <div
                  class="addproduct-icon d-flex align-items-center justify-content-between flex-fill"
                >
                  <h5 class="d-inline-flex align-items-center">
                    <i data-feather="info" class="feather-edit text-primary me-2"></i
                    ><span>Password</span>
                  </h5>
                  <a href="javascript:void(0);"
                    ><i data-feather="chevron-down" class="chevron-down-add"></i
                  ></a>
                </div>
              </div>
            </div>
            <div
              id="collapseTwo"
              class="accordion-collapse collapse show"
              aria-labelledby="heading6"
              data-bs-parent="#accordionExample"
            >
              <div class="accordion-body">
                <div class="pass-info">
                  <div class="row">
                    <div class="col-lg-4 col-md-6">
                      <div class="input-blocks mb-md-0 mb-sm-3">
                        <label>Password</label>
                        <div class="pass-group">
                          <input :type="showPassword ? 'text' : 'password'" class="form-control pass-input" value="12345678" />
                          <span class="toggle-password" @click="toggleShow">
                            <i
                              :class="{
                                'fas fa-eye': showPassword,
                                'fas fa-eye-slash': !showPassword,
                              }"
                            ></i>
                          </span>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                      <div class="input-blocks mb-0">
                        <label>Confirm Password</label>
                        <div class="pass-group">
                          <input :type="showPassword1 ? 'text' : 'password'" class="form-control pass-inputa" value="12345678" />
                          <span class="toggle-passworda" @click="toggleShow1">
                            <i
                              :class="{
                                'fas fa-eye': showPassword1,
                                'fas fa-eye-slash': !showPassword1,
                              }"
                            ></i>
                          </span>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /product list -->

        <div class="text-end mb-3">
          <button type="button" class="btn btn-secondary me-2">Cancel</button>
          <button type="submit" class="btn btn-primary">Save Changes</button>
        </div>
      </form>
    </div>

    <div
      class="footer d-sm-flex align-items-center justify-content-between border-top bg-white p-3"
    >
      <p class="mb-0">2014-2025 © DreamsPOS. All Right Reserved</p>
      <p>
        Designed &amp; Developed By
        <a href="javascript:void(0);" class="text-primary">Dreams</a>
      </p>
    </div>
  </div>
</template>
<script>
import { ref } from "vue";
const value1 = ref();
const value2 = ref();
import Quill from "quill";
import "quill/dist/quill.snow.css";

export default {
  data() {
    return {
      selected: "Male",
      selectedOne: "United Kingdom",
      selectedTwo: "Regular",
      selectedThree: "UI/UX",
      selectedFour: "Designer",
      selectedFive: "O Postive",
      selectedSix: "United Kingdom",
      selectedSeven: "California",
      selectedEight: "Los Angeles",
      ChooseEmpCou: [
        {label: "Choose", value: "Choose"}, 
        {label: "United Kingdom", value: "United Kingdom"}, 
        {label: "USA", value: "USA"}, 
      ],
      BloodEmp: [
        {label: "Choose", value: "Choose"}, 
        {label: "A+", value: "A+"}, 
        {label: "A-", value: "A-"}, 
        {label: "B+", value: "B+"}, 
        {label: "B-", value: "B-"}, 
        {label: "O+", value: "O+"}, 
        {label: "AB+", value: "AB+"}, 
        {label: "AB-", value: "AB-"}, 
      ],
      DesEmp: [
        {label: "Choose", value: "Choose"}, 
        {label: "Designer", value: "Designer"}, 
        {label: "Developer", value: "Developer"}, 
        {label: "Tester", value: "Tester"}, 
      ],
      DepEmp: [
        {label: "Choose", value: "Choose"}, 
        {label: "UI/UX", value: "UI/UX"}, 
        {label: "Support", value: "Support"}, 
        {label: "HR", value: "HR"}, 
        {label: "Enginnering", value: "Enginnering"}, 
      ],
      ChoEmp: [
        {label: "Choose", value: "Choose"}, 
        {label: "Regular", value: "Regular"}, 
      ],
      EmpNat: [
        {label: "Choose", value: "Choose"},
        {label: "United Kingdom", value: "United Kingdom"},
        {label: "India", value: "India"},
      ],
      Empmale: [
        {label: "Choose", value: "Choose"}, 
        {label: "Male", value: "Male"}, 
        {label: "Female", value: "Female"},
      ],
      ChooseEmpCityOne: [
        {label: "Choose", value: "Choose"}, 
        {label: "Los Angeles", value: "Los Angeles"}, 
        {label: "New Jersey", value: "New Jersey"}, 
      ],
      ChooseEmpStaOne: [
        {label: "Choose", value: "Choose"}, 
        {label: "California", value: "California"}, 
        {label: "Paris", value: "Paris"}
      ],
      value1,
      value2,
      showPassword: false,
      showPassword1: false,
    };
  },
  mounted() {
    this.initQuill();
  },
  computed: {
    buttonLabel() {
      return this.showPassword ? "Hide" : "Show";
    },
    buttonLabel1() {
      return this.showPassword1 ? "Hide" : "Show";
    },
  },
  methods: {
    toggleShow() {
      this.showPassword = !this.showPassword;
    },
    toggleShow1() {
      this.showPassword1 = !this.showPassword1;
    },
    toggleHeader() {
      document.getElementById("collapse-header").classList.toggle("active");
      document.body.classList.toggle("header-collapse");
    },
    initQuill() {
      const quill = new Quill(this.$refs.editorRef, {
        theme: "snow",
        modules: {
          toolbar: [
            [{ header: [1, 2, false] }],
            ["bold", "italic", "underline"],
            ["image", "code-block"],
          ],
        },
      });

      quill.on("text-change", () => {
        this.content = quill.root.innerHTML;
      });
    },
  },
};
</script>

// template/dreamspos-v2.2.4/nextjs-extracted/nextjs/template/src/components/hrm/editemployee.tsx
"use client";
/* eslint-disable @next/next/no-img-element */
import CollapesIcon from "@/core/common/tooltip-content/collapes";
import RefreshIcon from "@/core/common/tooltip-content/refresh";
import { all_routes } from "@/data/all_routes";
import { DatePicker } from "antd";
import { ArrowLeft, Calendar, PlusCircle } from "react-feather";
import Link from "next/link";
import { useState } from "react";
import Select from "react-select";
import DefaultEditor from "react-simple-wysiwyg";

export default function EditEmployeeComponent  ()  {
  const route = all_routes;

  const [passwordVisibility, setPasswordVisibility] = useState({
    password: false,
    confirmPassword: false,
  });

  const togglePasswordVisibility = (field:any) => {
    setPasswordVisibility((prevState:any) => ({
      ...prevState,
      [field]: !prevState[field],
    }));
  };


   const [values, setValue] = useState();
    function onChange(e:any) {
      setValue(e.target.value);
    }

  const gender = [
    { value: "Choose", label: "Choose" },
    { value: "Male", label: "Male" },
    { value: "Female", label: "Female" },
  ];
  const nationality = [
    { value: "Choose", label: "Choose" },
    { value: "United Kingdom", label: "United Kingdom" },
    { value: "India", label: "India" },
  ];
  const Shift = [
    { value: "Choose", label: "Choose" },
    { value: "Regular", label: "Regular" },
  ];
  const departments = [
    { value: "Choose", label: "Choose" },
    { value: "UI/UX", label: "UI/UX" },
    { value: "Support", label: "Support" },
    { value: "HR", label: "HR" },
    { value: "Engineering", label: "Engineering" },
  ];
  const designation = [
    { value: "Choose", label: "Choose" },
    { value: "Designer", label: "Designer" },
    { value: "Developer", label: "Developer" },
    { value: "Tester", label: "Tester" },
  ];
  const bloodgroup = [
    { value: "Select", label: "Select" },
    { value: "A+", label: "A+" },
    { value: "A-", label: "A-" },
    { value: "B+", label: "B-" },
    { value: "O+", label: "O-" },
    { value: "O+", label: "O-" },
    { value: "AB+", label: "AB-" },
    { value: "AB+", label: "AB-" },
  ];
  const country = [
    { value: "Choose", label: "Choose" },
    { value: "United Kingdom", label: "United Kingdom" },
    { value: "USA", label: "USA" },
  ];
  const state = [
    { value: "Choose", label: "Choose" },
    { value: "California", label: "California" },
    { value: "Paris", label: "Paris" },
  ];
  const city = [
    { value: "Choose", label: "Choose" },
    { value: "Los Angeles", label: "Los Angeles" },
    { value: "New Jersey", label: "New Jersey" },
  ];

  return (
    <div>
      <div className="page-wrapper">
        <div className="content">
          <div className="page-header">
            <div className="add-item d-flex">
              <div className="page-title">
                <h4>Edit Employee</h4>
                <h6>Create new Employee</h6>
              </div>
            </div>
            <ul className="table-top-head">
              <RefreshIcon />
              <CollapesIcon />
            </ul>
            <div className="page-btn">
              <Link href={route.employeelist} className="btn btn-secondary">
                <ArrowLeft className="me-2" />
                Back to List
              </Link>
            </div>
          </div>
          {/* /product list */}
          <form >
            <div className="accordions-items-seperate" id="accordionExample">
              <div className="accordion-item border mb-4">
                <h2 className="accordion-header" id="headingOne">
                  <div
                    className="accordion-button bg-white"
                    data-bs-toggle="collapse"
                    data-bs-target="#collapseOne"
                    aria-controls="collapseOne"
                  >
                    <div className="d-flex align-items-center justify-content-between flex-fill">
                      <h5 className="d-inline-flex align-items-center">
                        <i className="ti ti-users text-primary me-2" />
                        <span>Employee Information</span>
                      </h5>
                    </div>
                  </div>
                </h2>
                <div
                  id="collapseOne"
                  className="accordion-collapse collapse show"
                  aria-labelledby="headingOne"
                  data-bs-parent="#accordionExample"
                >
                  <div className="accordion-body border-top">
                    <div className="new-employee-field">
                      <div className="profile-pic-upload">
                        <div className="profile-pic">
                          <span>
                            <PlusCircle size={14} className="plus-down-add" />
                            Profile Photo
                          </span>
                        </div>
                        <div className="input-blocks mb-0">
                          <div className="image-upload mb-0">
                            <input type="file" />
                            <div className="image-uploads">
                              <h4>Change Image</h4>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="row">
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">
                              First Name<span className="text-danger ms-1">*</span>
                            </label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">
                              Last Name<span className="text-danger ms-1">*</span>
                            </label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">
                              Email<span className="text-danger ms-1">*</span>
                            </label>
                            <input type="email" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">
                              Contact Number
                              <span className="text-danger ms-1">*</span>
                            </label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">
                              Emp Code<span className="text-danger ms-1">*</span>
                            </label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="input-blocks">
                            <label className="form-label">
                              Date of Birth<span className="text-danger ms-1">*</span>
                            </label>
                            <div className="input-groupicon calender-input">
                              <Calendar className="info-img" />
                              <DatePicker
                                className="form-control datetimepicker"
                                placeholder="dd/mm/yyyy"
                              />
                            </div>
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">
                              Gender<span className="text-danger ms-1">*</span>
                            </label>
                            <Select
                              classNamePrefix="react-select"
                              options={gender}
                              placeholder="Choose"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">
                              Nationality<span className="text-danger ms-1">*</span>
                            </label>
                            <Select
                              classNamePrefix="react-select"
                              options={nationality}
                              placeholder="Choose"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="input-blocks">
                            <label>
                              Joining Date<span className="text-danger ms-1">*</span>
                            </label>
                            <div className="input-groupicon calender-input">
                              <Calendar className="info-img" />
                              <DatePicker
                                className="form-control datetimepicker"
                                placeholder="dd/mm/yyyy"
                              />

                            </div>
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <div className="add-newplus">
                              <label className="form-label">
                                Shift<span className="text-danger ms-1">*</span>
                              </label>
                              <Link href="#">
                                <span>
                                  <i
                                    data-feather="plus-circle"
                                    className="plus-down-add"
                                  />
                                  Add new
                                </span>
                              </Link>
                            </div>
                            <Select
                              classNamePrefix="react-select"
                              options={Shift}
                              placeholder="Choose"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">
                              Department<span className="text-danger ms-1">*</span>
                            </label>
                            <Select
                              classNamePrefix="react-select"
                              options={departments}
                              placeholder="Choose"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">
                              Designation<span className="text-danger ms-1">*</span>
                            </label>
                            <Select
                              classNamePrefix="react-select"
                              options={designation}
                              placeholder="Choose"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">
                              Blood Group<span className="text-danger ms-1">*</span>
                            </label>
                            <Select
                              classNamePrefix="react-select"
                              options={bloodgroup}
                              placeholder="Choose"
                            />
                          </div>
                        </div>
                      </div>
                      {/* Editor */}
                      <div className="col-lg-12">
                        <div className="input-blocks summer-description-box transfer mb-3">
                          <label>About</label>
                          <div id="summernote">
                            <DefaultEditor value={values} onChange={onChange} />

                          </div>
                          <p className="mt-1">Maximum 60 Characters</p>
                        </div>
                      </div>
                      {/* /Editor */}
                    </div>
                  </div>
                </div>
              </div>
              <div className="accordion-item border mb-4">
                <div className="accordion-header" id="headingThree">
                  <div
                    className="accordion-button bg-white"
                    data-bs-toggle="collapse"
                    data-bs-target="#collapseThree"
                    aria-controls="collapseThree"
                  >
                    <div className="d-flex align-items-center justify-content-between flex-fill">
                      <h5 className="d-inline-flex align-items-center">
                        <i
                          data-feather="map-pin"
                          className="feather-edit text-primary me-2"
                        />
                        <span>Address Information</span>
                      </h5>
                    </div>
                  </div>
                </div>
                <div
                  id="collapseThree"
                  className="accordion-collapse collapse show"
                  aria-labelledby="headingThree"
                  data-bs-parent="#accordionExample"
                >
                  <div className="accordion-body border-top">
                    <div className="other-info">
                      <div className="row">
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">Address</label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">Country</label>
                            <Select
                              classNamePrefix="react-select"
                              options={country}
                              placeholder="Choose"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">State</label>
                            <Select
                              classNamePrefix="react-select"
                              options={state}
                              placeholder="Choose"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">City</label>
                            <Select
                              classNamePrefix="react-select"
                              options={city}
                              placeholder="Choose"
                            />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">Zipcode</label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="accordion-item border mb-4">
                <div className="accordion-header" id="heading4">
                  <div
                    className="accordion-button bg-white"
                    data-bs-toggle="collapse"
                    data-bs-target="#collapseFour"
                    aria-controls="collapseFour"
                  >
                    <div className="d-flex align-items-center justify-content-between flex-fill">
                      <h5 className="d-inline-flex align-items-center">
                        <i
                          data-feather="info"
                          className="feather-edit text-primary me-2"
                        />
                        <span>Emergency Information</span>
                      </h5>
                    </div>
                  </div>
                </div>
                <div
                  id="collapseFour"
                  className="accordion-collapse collapse show"
                  aria-labelledby="heading4"
                  data-bs-parent="#accordionExample"
                >
                  <div className="accordion-body border-top">
                    <div className="other-info">
                      <div className="row">
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">
                              Emergency Contact Number 1
                            </label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">Relation</label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">Name</label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">
                              Emergency Contact Number 2
                            </label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">Relation</label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">Name</label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="accordion-item border mb-4">
                <div className="accordion-header" id="heading5">
                  <div
                    className="accordion-button bg-white"
                    data-bs-toggle="collapse"
                    data-bs-target="#collapseFive"
                    aria-controls="collapseFive"
                  >
                    <div className="d-flex align-items-center justify-content-between flex-fill">
                      <h5 className="d-inline-flex align-items-center">
                        <i className="ti ti-building-bank feather-edit text-primary me-2" />
                        <span>Bank Information</span>
                      </h5>
                    </div>
                  </div>
                </div>
                <div
                  id="collapseFive"
                  className="accordion-collapse collapse show"
                  aria-labelledby="heading5"
                  data-bs-parent="#accordionExample"
                >
                  <div className="accordion-body border-top">
                    <div className="other-info">
                      <div className="row">
                        <div className="col-lg-3 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">Bank Name</label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-3 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">Account Number</label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-3 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">IFSC</label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                        <div className="col-lg-3 col-md-6">
                          <div className="mb-3">
                            <label className="form-label">Branch</label>
                            <input type="text" className="form-control" />
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div className="accordion-item border mb-4">
                <div className="accordion-header" id="heading6">
                  <div
                    className="accordion-button bg-white"
                    data-bs-toggle="collapse"
                    data-bs-target="#collapseTwo"
                    aria-controls="collapseTwo"
                  >
                    <div className="d-flex align-items-center justify-content-between flex-fill">
                      <h5 className="d-inline-flex align-items-center">
                        <i
                          data-feather="info"
                          className="feather-edit text-primary me-2"
                        />
                        <span>Password</span>
                      </h5>
                    </div>
                  </div>
                </div>
                <div
                  id="collapseTwo"
                  className="accordion-collapse collapse show"
                  aria-labelledby="heading6"
                  data-bs-parent="#accordionExample"
                >
                  <div className="accordion-body border-top">
                    <div className="pass-info">
                      <div className="row">
                        <div className="col-lg-4 col-md-6">
                          <div className="">
                            <label className="form-label">
                              Password <span className="text-danger"> *</span>
                            </label>
                            <div className="pass-group">
                              <input
                                type={passwordVisibility ? "text" : "password"}
                                className="pass-input form-control"
                              />
                              <span
                                className={`ti toggle-password ${passwordVisibility.password ? "ti-eye" : "ti-eye-off"
                                  }`}
                                onClick={togglePasswordVisibility}
                              ></span>
                            </div>
                          </div>
                        </div>
                        <div className="col-lg-4 col-md-6">
                          <div className="">
                            <label className="form-label">
                              Confirm Password <span className="text-danger"> *</span>
                            </label>
                            <div className="pass-group">
                              <input
                                type={
                                  passwordVisibility.confirmPassword ? "text" : "password"
                                }
                                className="pass-input form-control"
                              />
                              <span
                                className={`ti toggle-password ${passwordVisibility.confirmPassword
                                  ? "ti-eye"
                                  : "ti-eye-off"
                                  }`}
                                onClick={() =>
                                  togglePasswordVisibility("confirmPassword")
                                }
                              ></span>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* /product list */}
            <div className="text-end mb-3">
              <button type="button" className="btn btn-secondary me-2">
                Cancel
              </button>
              <button type="submit" className="btn btn-primary">
                Add Employee
              </button>
            </div>
          </form>
        </div>
        <div className="footer d-sm-flex align-items-center justify-content-between border-top bg-white p-3">
          <p className="mb-0">2014 - 2025 © DreamsPOS. All Right Reserved</p>
          <p>
            Designed &amp; Developed by{" "}
            <Link href="javascript:void(0);" className="text-primary">
              Dreams
            </Link>
          </p>
        </div>
      </div>

    </div>
  );
};
